cad: []
description: Mount for RAMPS board with the stepper extender
images: []
mod_version: 1
printer_compatibility:
- V1.6
- V2.1
- V2.2
stl:
- RAMPS-Extender_Halter_2_v4.stl
title: RAMPS Extender Holder
