cad:
- CAD/MagneticExhaustGrillCover.f3d
- CAD/MagneticExhaustGrillCover.step
description: A magnetic cover to seal the filtered exhaust
images:
- Images/foam_install.jpg
- Images/render_back.png
- Images/render_front.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/exhaust_filter_cover.stl
- STL/exhaust_filter_grill_modified.stl
title: Magnetic Exhaust Grill Cover
