cad:
- CAD/C270_assembly.step
- CAD/C270_assembly.f3d
description: Logitech C270 webcam front-centre mount
images:
- Images/C270_mount.png
- Images/C270_pin.jpg
- Images/C270_focusing_ring.png
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- STL/C270_focus_wheel.stl
- STL/C270_mount.stl
title: C270 mount
