cad:
- CAD/NewLatch_v108.f3d
description: Quick release panel latch inspired by the work of others.
images:
- Images/Latch-v68-3mm.jpg
- Images/Assembly.gif
- Images/BuildPlate.png
- Images/Parameters.png
- Images/250Plate.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/NewLatch-3.0mm.stl
- STL/NewLatch-3.5mm.stl
- STL/NewLatch-4.0mm.stl
- STL/NewLatch-4.5mm.stl
- STL/NewLatch-5.0mm.stl
- STL/NewLatch-5.5mm.stl
- STL/NewLatch-6.0mm.stl
- STL/NewLatch-6.5mm.stl
- STL/NewLatch-7.0mm.stl
- STL/NewLatch-7.5mm.stl
- STL/NewLatch-8.0mm.stl
- STL/NewLatch-8.5mm.stl
title: Printable snap latches for 2020 extrusion
