cad: []
description: Mount a 4-inch LCD touchscreen to your V2.4 in place of the usual 12864
  panel to allow you to run the amazing OctoDash touch UI
images:
- img/photo.jpg
- img/printorientation.jpg
- img/pcb.jpg
- img/cad.jpg
- img/attachbottompanel.jpg
- img/screenshots.jpg
- img/pushbuttonlocation.jpg
- img/removesupports.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/4-inch_lcd_display_frame_lower.stl
- STL/4-inch_lcd_display_frame_upper.stl
- STL/4-inch_lcd_display_push_button.stl
title: Touchscreen for OctoDash
