cad: []
description: This Mod is a simple "One Piece" mount for the popular Electreeks Camera.
images:
- Pictures/Picture1.jpeg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/Mount_for_Electreeks_Cam.stl
title: Mount for Electreeks Camera
