cad: []
description: AngryLED - LED-mount for Lumentech LT3 profiles.
images:
- AngryLED_v1_2.png
- AngryLED_v1_1.png
- AngryLED_v1_3.png
- led_mount_v01_2.png
- led_mount_v01_1.png
- AngryLED_small_v1.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- AngryLED_l_v1.stl
- AngryLED_r_v1.stl
- AngryLED_small_l_v1.stl
- AngryLED_small_r_v1.stl
- LED_mount_l_v01.stl
- LED_mount_r_v01.stl
title: LED mount
