cad: []
description: V2 panel corner frames using 3-way L brackets in the corners
images: []
mod_version: 1
printer_compatibility:
- V2.4
stl:
- corner_panel_clip_3mm.stl
- corner_panel_clip_6mm.stl
title: Corner panel clip
