cad:
- STEP/VoronV0_CableManagementDuct.step
description: Zip tie mount intergrated cable duct to hide your cable
images:
- Images/VORON_V0.1_cable_management_duct_flat.png
- Images/VORON_V0.1_cable_management_duct.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/CableDuctBody.stl
- STLs/CableDuctBody_small.stl
- STLs/CableDuctCover.stl
- STLs/CableDuctCover_nologo_small.stl
- STLs/CableDuctCover_small.stl
title: Cable Management Duct
