cad:
- CAD/15x15_Drag_Chain_End.f3d
description: 15x15 drag chain end piece
images:
- Images/Image.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/15x15_Drag_Chain_End.stl
title: 15x15 Drag Chain End
