cad:
- CAD/v02_rear_skirt_keystone.step
description: Added keystone slot on rear skirt for V0.2
images:
- Images/1.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/v02_rear_skirt_keystone.stl
title: Voron0.2 Rear Keystone Skirt
