cad:
- AB_dial_indicator_mount.step
description: Mount for attaching standard dial indicators to AB
images:
- image1.png
- image2.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
stl:
- AB_dial_indicator_mount.stl
title: AB dial indicator mount
