cad:
- CAD/LCD_RearCover.STEP
- CAD/LCD_Hinge.STEP
- CAD/LCD_Accent.STEP
- CAD/LCD_Assembly.STEP
- CAD/LCD_Front.STEP
- CAD/Mini12864_LCD_Screen.STEP
- CAD/Alternative_base_(No_Heatset_Inserts)/LCD_Front_holes.STEP
description: Swiveling case for the Fysetc Mini12864 LCD
images:
- Images/LCD_Detailed.jpg
- Images/LCD_SwivelDown.jpg
- Images/LCD_BackCover.jpg
- Images/LCD_SwivelUp.jpg
- Images/LCD_CAD.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- base.STL
- rear_cover.STL
- '[a]_display_cover.STL'
- '[a]_hinge.stl'
- CAD/Alternative_base_(No_Heatset_Inserts)/LCD_Front_holes.STL
title: Mini12864 LCD Mount
