cad: []
description: A mount for the BTT PITFT50 v2 Touch Display
images:
- images/IMG_6451.jpg
- images/f360.jpg
- images/IMG_6447.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/BTT-PITFT50-v2-Mount.stl
title: BTT PITFT50 v2 Mount
