cad: []
description: v2.4 magnetic clips to retain bottom panel
images:
- bottom_panel_maghold.jpg
- bottom_panel_maghold_panel.jpg
- bottom_panel_maghold_skirt.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- bottom_panel_magclip_skirt_x6.stl
- bottom_panel_maghold_panel_x6.stl
title: Bottom Panel Mag Clip
