cad: []
description: 25mm skirt panel with integrated keystone jack.  Use with 50mm smaller
  adjacent skirts for proper fit.
images: []
mod_version: 1
printer_compatibility:
- V2.2
stl:
- skirt_keystone_jack.stl
title: Keystone Skirt Panel
