cad:
- CAD/Filament_Runout_Housing.f3d
description: Filament runout sensor that replaces the stock bowden retainer
images:
- IMAGES/Internal_Assembly.png
- IMAGES/Switch_Cross_Section.png
- IMAGES/Assembled.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STL/Cover.stl
- STL/LH_Filament_Runout_Housing.stl
- STL/RH_Filament_Runout_Housing.stl
title: Filament Runout Sensor
