cad:
- step/v0_foot_skirt_right.step
- step/v0_foot_skirt_left.step
description: V0 C14 Skirt inlet
images:
- img/V0_inlet1.jpg
- img/V0_inlet2.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- skirt_Inlet.stl
- skirt_Inlet_mirror.stl
title: V0 c14 Skirt Inlet
