cad: []
description: v2.4 plug panel for generic unfiltered modules with 66mm x 27mm cutout
  such as the Delta 06A2 and Qualtek 761-18
images:
- Images/1.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/Plug_Panel_Generic.stl
title: Plug Panel Mod for Generic Unfiltered Modules
