cad:
- F6_Dual_Frame.f3d
description: Mounts for FYSETCS F6 controller boards
images: []
mod_version: 1
printer_compatibility:
- V1.6
- V2.1
- V2.2
stl:
- dual_F6_V13_frame_a.stl
- dual_F6_V13_frame_b.stl
title: F6 Board Mount
