cad:
- KiCad/LED_WS2812_2020.step
description: A small RGB LED grid for Stealthburner's logo
images:
- IMG_2805.gif
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl: []
title: RGB LED grid for Stealthburner
