cad:
- LED_Bar_Clip_Misumi_version2.step
- LED_Bar_Clip_Misumi_version2.f3d
description: Modular LED Clip for mounting LED Strip to 2020 Extrusions
images: []
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- LED_Bar_Clip_Misumi_version2.stl
title: LED Bar Clip
