cad:
- CAD/Belttool.f3d
description: Belt tension helper for V0.1
images:
- Images/Belttool-img2.jpg
- Images/Belttool-img1.jpg
- Images/Belttool-img3.jpg
- Images/Tension_tool_drawing.PNG
- Images/Belttool-img6.jpg
- Images/Belttool-img5.jpg
- Images/Belttool-img4.jpg
- Images/Belttool-img3text2.jpg
- Images/Belttool-img5text.jpg
- Images/Tension_tool_slicing.PNG
- Images/Belttool-img1text.jpg
- Images/Belttool-img1text2.jpg
- Images/Belttool-img3text.jpg
- Images/Belttool-img2text.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/belttool-btm_v2.stl
- STL/belttool-top_v2.stl
title: Belt tension helper
