cad: []
description: A modified plug panel for the Power Entry Connector Schaffner FN286-10-06
  with two integreated Keystone sockets.
images:
- IMG_20201201_164633.jpg
- IMG_20201201_164639.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- plug_panel_v6.stl
title: Plug Panel Mod for Schaffner FN286-10-06
