cad:
- CAD/Guide_x2.stp
- CAD/case_front.stp
- CAD/case_rear.stp
- CAD/claw_bottom.stp
- CAD/claw_top.stp
- CAD/slider.stp
description: This mod allows the use of different smartphones or possibly tablets
  that you may want to use for klipperscreen.
discord_username: AVieira
images:
- Images/CAD_parts/case_front.png
- Images/CAD_parts/case_rear.png
- Images/CAD_parts/claw_bottom.png
- Images/CAD_parts/claw_top.png
- Images/CAD_parts/guide_x2.png
- Images/CAD_parts/mini12864_case_hinge.png
- Images/CAD_parts/slider.png
- Images/246.png
- Images/248.png
- Images/250.png
- Images/Assembly_Mounted.jpg
- Images/Assembly_Mounted_With_Galaxy_A3.jpg
- Images/Back.jpg
- Images/Back_Inserts.jpg
- Images/CAD_Clearence.png
- Images/CAD_Clearence_2.png
- Images/CAD_Exploded.png
- Images/Elastic_Band.jpg
- Images/Front_Inserts.jpg
- Images/Full.jpg
- Images/Samsung_A3.jpg
- Images/Samsung_Galaxy_Mini_S5570.jpg
- Images/Size.png
- Images/Slider_Elastic.jpg
- Images/Slider_Elastic_Main_Assembly.jpg
- Images/Slider_Inserts.jpg
- Images/case_front.png
mod_version: 1
printer_compatibility:
- V2.4r2
stl:
- STLs/case_front.stl
- STLs/case_rear.stl
- STLs/Guide_x2.stl
- STLs/Claw_bottom/[a]_claw_bottom_10.5mm.stl
- STLs/Claw_bottom/[a]_claw_bottom_11.5mm.stl
- STLs/Claw_bottom/[a]_claw_bottom_12.5mm.stl
- STLs/Claw_bottom/[a]_claw_bottom_13.5mm.stl
- STLs/Claw_bottom/[a]_claw_bottom_6.5mm.stl
- STLs/Claw_bottom/[a]_claw_bottom_7.5mm.stl
- STLs/Claw_bottom/[a]_claw_bottom_8.5mm.stl
- STLs/Claw_bottom/[a]_claw_bottom_9.5mm.stl
- STLs/Claw_top/[a]_claw_top_10.5mm.stl
- STLs/Claw_top/[a]_claw_top_11.5mm.stl
- STLs/Claw_top/[a]_claw_top_12.5mm.stl
- STLs/Claw_top/[a]_claw_top_13.5mm.stl
- STLs/Claw_top/[a]_claw_top_6.5mm.stl
- STLs/Claw_top/[a]_claw_top_7.5mm.stl
- STLs/Claw_top/[a]_claw_top_8.5mm.stl
- STLs/Claw_top/[a]_claw_top_9.5mm.stl
- STLs/Slider/slider_100mm.stl
- STLs/Slider/slider_150mm.stl
- STLs/Slider/slider_170mm.stl
- STLs/Slider/slider_190mm.stl
- STLs/Slider/slider_80mm.stl
- STLs/Slider/slider_90mm.stl
title: Universal_Phone_Mount
