cad:
- 10x11 Chain Bottom Anchor.step
- 10x11 Chain Top Anchor.step
- 10x15 Chain Bottom Anchor.step
- 10x15 Chain Top Anchor.step
description: Cable chain ends to use off the shelf chains with Voron parts
images:
- 10x15-cable-chain.jpg
mod_version: 1
printer_compatibility:
- V2.1
- V2.2
stl:
- 10x11_Chain_Bottom_Anchor.stl
- 10x11_Chain_Top_Anchor.stl
- 10x15_Chain_Bottom_Anchor.stl
- 10x15_Chain_Top_Anchor.stl
title: Openbuild chain ends
