cad:
- Hinges.f3d
- Hinges.step
description: Door hinges that use an M3 bolt for a pin and bolts thru the panel
images:
- Images/photo_2.jpg
- Images/image_2.png
- Images/photo_1.jpg
- Images/image_3.png
- Images/image_1.png
- Images/photo_3.jpg
- Images/image_4.png
- Images/photo_7.jpg
- Images/photo_6.jpg
- Images/image_5.png
- Images/photo_4.jpg
- Images/photo_5.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- door_handle_a_x2.stl
- door_handle_b_x2.stl
- door_latch_x2.stl
- drill_guide_handle_a.stl
- drill_guide_handle_b.stl
- drill_guide_hinge.stl
- hinge_arm_a_x2.stl
- hinge_arm_b_x2.stl
- hinge_backplate_x4.stl
- hinge_pivot_x4.stl
title: Door Hinges
