cad: []
description: For any cutting machines or machines that rely on vector graphics and
  use .svg files. These vectors or .svg files are the Voron Design Logos for the Voron
  2.4, Voron SwitchWire, Voron 0.0/0.1. and Trident These .svg files use a minimal
  amount of anchor points to achieve the vector shapes!
images:
- images/V2.4_1Color.jpg
- VSWL/1ColorLayerWOLogoWOSil/VSWRearPWOWOSilBackP.jpg
- VSWL/1ColorLayerWOLogoWOSil/VSWRearPWOWOSil.jpg
- VSWL/1ColorLayerWOLogoWOSil/VSWRearPWOWOSil.svg
- VSWL/1ColorLayerWOLogoWithSil/VSWRearPWOWithSil.svg
- VSWL/1ColorLayerWOLogoWithSil/VSWRearPWOWithSil.jpg
- VSWL/1ColorLayer/VSWRearP.svg
- VSWL/1ColorLayer/VSWRearPlay.svg
- VSWL/1ColorLayer/VSWRearP.jpg
- VSWL/1ColorLayer/VSWRearP.png
- images/V0.1woWOSilBackP.jpg
- images/Trident_DLogo.png
- images/QWComplexVL.jpg
- images/CombinedRedPath.png
- images/V0.1woWOSil.jpg
- images/V2.4_1ColorWOWithSil.jpg
- images/Trident_DLogo_250_Rear_Panel.stl.png
- images/VSWRearPWOWOSilhBackP.jpg
- images/Trident_DLogo_CAD.stl.png
- images/VSWRearP.jpg
- images/V0.1woWithSil.jpg
- images/QWPlainVL2.png
- images/QWPlainVL.png
- images/Trident_DLogo_WOHexOutline2jpg.jpg
- images/V2.4_1ColorWOWOSil.jpg
- images/VSWRearPWOWOSil.jpg
- images/VDesignPlainL.jpg
- images/250_rear.jpg
- images/VSWRearPWOWithSil.jpg
- images/V2.4_3Color.jpg
- VPlainL/1ColorLayer/VDesignPlainLorig.png
- VPlainL/1ColorLayer/VDesignPlainL[Converted].svg
- VPlainL/1ColorLayer/VDesignPlainL.png
- VPlainL/1ColorLayer/VDesignPlainL.jpg
- V2.4QueenL/QWComplexVL/QWComplexVL.jpg
- V2.4QueenL/QWComplexVL/QWComplexVL.svg
- V2.4QueenL/QWComplexVL/QWComplexVLBackP_RGB.jpg
- V2.4QueenL/QWComplexVL/V2.4_3Color.svg
- V2.4QueenL/QWiPlainVL/VDesignPlainLConverted.svg
- V2.4QueenL/QWiPlainVL/AllPaths[Converted].svg
- V2.4QueenL/QWiPlainVL/QWPlainVL.png
- V2.4QueenL/QWPlainVL2/QWPlainVL2.png
- V2.4QueenL/QWPlainVL2/QWPlainVL2.svg
- V2.4QueenL/V2.4BackPanel/V2.4_3ColorBackP_RGB.jpg
- V2.4QueenL/V2.4BackPanel/V2.4_3Color.svg
- V2.4QueenL/V2.4BackPanel/V2.4_3Color.jpg
- V2.4L/3ColorLayers/V2.4_3ColorBackP_RGB.jpg
- V2.4L/3ColorLayers/V2.4_3Color.svg
- V2.4L/3ColorLayers/V2.4_3Color.jpg
- V2.4L/1ColorLayerWOWithSil/V2.4_1ColorWOWithSil.svg
- V2.4L/1ColorLayerWOWithSil/V2.4_1ColorWOWithSil.jpg
- V2.4L/1ColorLayer/V2.4_1Color.svg
- V2.4L/1ColorLayer/V2.4_1Color.jpg
- V2.4L/1ColorLayer/1Color900ppiB&W.jpg
- V2.4L/1ColorLayerWOWOSil/V2.4WOWOSil.svg
- V2.4L/1ColorLayerWOWOSil/V2.4WOWOSil.jpg
- V0.1L/1ColorLayerWOWithSil/V0.1WOWithSil.svg
- V0.1L/1ColorLayerWOWithSil/V0.1WOWithSil.jpg
- V0.1L/1ColorLayer/CombinedRedPathLay.png
- V0.1L/1ColorLayer/Boarderonly.svg
- V0.1L/1ColorLayer/CombinedRedPath.svg
- V0.1L/1ColorLayer/CombinedRedPathLay.svg
- V0.1L/1ColorLayer/Partsonly.svg
- V0.1L/1ColorLayer/CombinedRedPathLayout.png
- V0.1L/1ColorLayer/CombinedRedPathLayout.svg
- V0.1L/1ColorLayerWOWOSil/V0.1WOWOSilBackP.jpg
- V0.1L/1ColorLayerWOWOSil/V0.1WOWOSil.jpg
- V0.1L/1ColorLayerWOWOSil/V0.1WOWOSil.svg
- Voron_Trident/.stl_files/Trident_DLogo_250_deck_Panel.stl.png
- Voron_Trident/.stl_files/Trident_DLogo_250_Rear_Panel.stl.png
- Voron_Trident/.stl_files/Trident_DLogo_350_deck_Panel.stl.png
- Voron_Trident/.stl_files/Trident_DLogo_300_deck_Panel.stl.png
- Voron_Trident/RD_ALL_correct_dim/250_rear.jpg
- Voron_Trident/1ColorLayer/Trident_DLogo.png
- Voron_Trident/1ColorLayer/Trident_DLogo_WHex_CPaths.svg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/250_Panels_SVG_Files/Trident_DLogo_250_rear_WithHex.svg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/250_Panels_SVG_Files/Trident_DLogo_250_deck_WithHex.svg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/250_Panels_SVG_Files/Trident_DLogo_250_deck_WithHex.jpg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/250_Panels_SVG_Files/Trident_DLogo_250_rear_WithHex.jpg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/300_Panels_SVG_Files/Trident_DLogo_300_rear_WithHex.jpg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/300_Panels_SVG_Files/Trident_DLogo_300_deck_WithHex.jpg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/300_Panels_SVG_Files/Trident_DLogo_300_deck_WithHex.svg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/300_Panels_SVG_Files/Trident_DLogo_300_rear_WithHex.svg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/350_Panels_SVG_Files/Trident_DLogo_350_rear_WithHex.jpg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/350_Panels_SVG_Files/Trident_DLogo_350_deck_WithHex.jpg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/350_Panels_SVG_Files/Trident_DLogo_350_deck_WithHex.svg
- Voron_Trident/1ColorLayer/.svg_files_diff_Panels/350_Panels_SVG_Files/Trident_DLogo_350_rear_WithHex.svg
- Voron_Trident/1ColorLayerWOWOSil/Trident_DLogo_WOHex_CPath.svg
- Voron_Trident/1ColorLayerWOWOSil/Trident_DLogo_WOHexOutline2jpg.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_DLogo_250_deck.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_DLogo_250_rear.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_300_SVG_Files/Trident_DLogo_300_rear.svg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_300_SVG_Files/Trident_DLogo_300_deck.svg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_300_SVG_Files/Trident_DLogo_300_deck.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_300_SVG_Files/Trident_DLogo_300_rear.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_350_SVG_Files/Trident_DLogo_350_deck.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_350_SVG_Files/Trident_DLogo_350_rear.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_350_SVG_Files/Trident_DLogo_350_rear.svg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_350_SVG_Files/Trident_DLogo_350_deck.svg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_250_SVG_Files/Trident_DLogo_250_deck.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_250_SVG_Files/Trident_DLogo_250_rear.jpg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_250_SVG_Files/Trident_DLogo_250_rear.svg
- Voron_Trident/1ColorLayerWOWOSil/.svg_files_diff_Panels/Trident_250_SVG_Files/Trident_DLogo_250_deck.svg
mod_version: 1
printer_compatibility:
- V0.2
- V2.4
- VSW
- VT
stl:
- Voron_Trident/.stl_files/Trident_DLogo.stl
- Voron_Trident/.stl_files/Trident_DLogo_250_deck_Panel.stl
- Voron_Trident/.stl_files/Trident_DLogo_250_Rear_Panel.stl
- Voron_Trident/.stl_files/Trident_DLogo_300_deck_Panel.stl
- Voron_Trident/.stl_files/Trident_DLogo_300_rear_Panel.stl
- Voron_Trident/.stl_files/Trident_DLogo_350_deck_Panel_.stl
- Voron_Trident/.stl_files/Trident_DLogo_350_rear_Panel.stl
- Voron_Trident/.stl_files/Trident_DLogo_Dim_X_216.51_Y_250.00_Z_1.75.stl
- Voron_Trident/.stl_files/Trident_DLogo_Dim_X_259.80_Y_300.00_Z_2.10.stl
- Voron_Trident/.stl_files/Trident_DLogo_Dim_X_303.12_Y_350.00_Z_2.46.stl
title: Cricut Voron Logos
