cad:
- CAD/PITFT50_45_degree_mount.f3d
- CAD/PITFT50_45_degree_mount.step
description: Mount that puts the screen at a 45-degree angle for more vertical clearance
images:
- Images/side-view.jpeg
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- STL/PITFT50_45_degree_mount.stl
title: PITFT50 45-degree mount
