cad:
- CAD/NozzleWiper.step
description: Servo powered nozzle wiper and purge bucket
images:
- images/fullyopen.jpg
- images/completed.jpg
- images/brush.jpg
- images/armtobrushmount.jpg
- images/armassembly.jpg
- images/mounted.jpg
- images/parts.jpg
- images/brushholder.jpg
- images/servomounting.jpg
- images/bucket.jpg
- images/armtomount.jpg
- images/NozzleWiper.gif
- images/servosetting.jpg
- images/wireplacement.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/Allinone.stl
- STLs/Brush_Carrier.stl
- STLs/Carrier_Joint.stl
- STLs/Parallel_Arm.stl
- STLs/Purge_Bucket.stl
- STLs/Servo_Arm.stl
- STLs/Servo_Joint.stl
- STLs/Servo_Mount.stl
title: V0.1 Nozzle Wiper
