cad:
- Parametric_Filtered_Power_v1.8.f3d
description: V1.6 Filtered Inlet and Rocker Switch for V1.8
images:
- pictures/Front.png
- pictures/Back.png
mod_version: 1
printer_compatibility:
- V1.8
stl:
- skirt_250_filtered_power.stl
- skirt_300_filtered_power.stl
title: V1.8 Filtered Power Inlet
