cad:
- CAD/Front_Bed_Mount.f3d
description: Printed bed front for kirigami folded metal bed mount with Voron logo.
images: []
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/Front_Bed_Mount_x1.stl
title: Kirigami bed front
