cad:
- cad/2020-Wago_221-412_tray-5x2.step
description: Smaller 5 port Wago mount that fits parallel to the support rails
images:
- images/Installed_Older_Version.jpg
- images/5x2_front_view.png
- images/5x2_back_view.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- stl/2020-Wago_221-412_tray-5x2.stl
title: Wago mount
