cad: []
description: A simple safety guard for the terminals on a Crydom GN SSR
images:
- Images/installed.jpg
- Images/guard.png
- CAD/lightning.svg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/crydom-gn-guard.stl
title: Crydom GN Terminal Guard
