cad:
- pocket_watch_rear_mount.step
description: Pocket watch rear reolcation bracket
images: []
mod_version: 1
printer_compatibility:
- V0.2
stl:
- pocket_watch_rear_mount.stl
title: Pocket Watch Rear Reolcation Bracket
