cad:
- CAD/Mini-After-LGX-lite.step
- CAD/Z_Bed_adjustable_Y_offset.step
description: LGX Lite Toolhead Setup For Voron V0.1.
images:
- Images/mini-after-lgx-lite_header-1200x628.jpg
- Images/PTFE-Cutting-Jig.jpg
- Images/Hotend-Mount-Mosquito-3010-Fan.png
- Images/Cowling-Universal.png
- Images/Hotend-Mount-Copperhead-Screw-Mount-3007-Fan.png
- Images/Hotend-Mount-DRAGON-3007-Fan.png
- Images/Hotend-Mount-DRAGONFLY-3007-Fan.png
- Images/X-Carriage.png
- Images/Hotend-Mount-MOSQUITO-3007-Fan.png
- Images/Hotend-Mount-DRAGONFLY-3010-Fan.png
- Images/Hotend-Mount-Copperhead-Screw-Mount-3010-Fan.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/Mini-After-LGX-lite/cowling_universal.stl
- STL/Mini-After-LGX-lite/cowling_universal_sls.stl
- STL/Mini-After-LGX-lite/hotend_mount_copperhead_screw_mount_3007_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_copperhead_screw_mount_3010_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_dragonfly_3007_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_dragonfly_3010_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_dragon_3007_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_mosquito_3007_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_mosquito_3010_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_revo-voron_3007_fan.stl
- STL/Mini-After-LGX-lite/hotend_mount_revo-voron_3010_fan.stl
- STL/Mini-After-LGX-lite/klicky.stl
- STL/Mini-After-LGX-lite/strain_relief.stl
- STL/Mini-After-LGX-lite/strain_relief_spacer_x2.stl
- STL/Mini-After-LGX-lite/strain_relief_spacer_x2_trisert-136.stl
- STL/Mini-After-LGX-lite/x-carriage_sls.stl
- STL/Mini-After-LGX-lite/x-carriage_sls_trisert-136.stl
- STL/Mini-After-LGX-lite/x-carriage_supported.stl
- STL/Tools/adafruit_adxl345_spacer.stl
- STL/Tools/adxl345_generic_mount.stl
- STL/Tools/ptfe_cutting_jig.stl
- STL/Z_Bed_adjustable_Y_offset/Front_Bed_Mount.stl
- STL/Z_Bed_adjustable_Y_offset/Front_Bed_Mount_lgx_lite_spacer.stl
- STL/Z_Bed_adjustable_Y_offset/Rear_Bed_Mount_Left.stl
- STL/Z_Bed_adjustable_Y_offset/Rear_Bed_Mount_Left_lgx_lite_spacer.stl
- STL/Z_Bed_adjustable_Y_offset/Rear_Bed_Mount_Right.stl
- STL/Z_Bed_adjustable_Y_offset/Rear_Bed_Mount_Right_lgx_lite_spacer.stl
title: Mini-After-LGX-Lite
