cad:
- 3D/Voron_V2.4_Pull-out_electrical_store.STEP
description: "Voron 2.4 Pull-out electrical store\uFF08350mm only\uFF09"
images:
- Photos/Voron_V2.4_Pull-out_electrical_store.PNG
- Photos/IMG_6101.jpg
- Photos/IMG_6103.jpg
- Photos/IMG_6107.jpg
- Photos/IMG_6099.jpg
- Photos/IMG_6105.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/Fan_decorative_panel_X2.STL
- STL/Front_L_350_X1.STL
- STL/Front_R_350_X1.STL
- STL/Mini12864_Case_Assembly_X1.STL
- STL/Side_L_350_X2.STL
- STL/Side_R_350_X2.STL
title: Pull-out electrical store
