cad:
- DIODER_led_strip_mount.STEP
description: Led strip mount for Ikea Dioder
images:
- Mount_view.jpg
- Top_light_view.jpg
mod_version: 1
printer_compatibility:
- V2.2
stl:
- DIODER_led_strip_mount.STL
title: Led strip mount DIODER
