cad:
- CAD/Tophead_Mod_V0_v4.f3d
description: A mount for 10mm LED strips and Exhaust for Voron V0
images:
- img/Foto_2.jpg
- img/Foto_1.jpg
- img/LED_Light_4.PNG
- img/LED_Light_5.PNG
- img/LED_Light_1.PNG
- img/LED_Light_2.PNG
- img/LED_Light_3.PNG
- img/Konstruktion_1.PNG
- img/Konstruktion_3.PNG
- img/Konstruktion_2.PNG
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/Skirt_12mm_switch.stl
- STL/Exhaust/Exhaust_without_Holes.stl
- STL/Exhaust/Exhaust_with_Holes.stl
- STL/Exhaust/[a]Exhaust_Cover.stl
- STL/LED_Light/LED_Carrier.stl
- STL/LED_Light/LED_Carrier_mirror.stl
- STL/LED_Light/[a]_LED_Cover_2x.stl
- STL/LED_Light/[a]_LED_Mountigplatte_2x.stl
title: TopHat Exhaust and LED Light
