cad:
- CAD/VORON2_v2.4_Exhaust_Adapter_100mm_RC3.step
description: Replace 60mm exhaust fan with 100mm ventilation system adapter
images:
- Images/Exhaust_Adapter_ISO_rendered_bright.png
- Images/Exhaust_Adapter_sideview.png
- Images/Exhaust_Adapter_ISO.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STL/VORON2_v2.4_Exhaust_Adapter_100mm_RC3.stl
title: Exhaust Adapter 100mm
