cad: []
description: Voron V0 Mean Well power supply bracket (Funssor Kit)
images:
- Voron_V0_MW_PS_Bracket.jpg
- Voron_V0_MW_PS_Bracket_v7_2.png
- Voron_V0_MW_PS_Bracket_v7_1.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Voron_V0_MW_PS_Bracket.stl
title: Voron V0 Mean Well power supply bracket (Funssor Kit)
