cad:
- CAD/Gantry/X_Axis/X_Carriage/MGN12Umblilcal.step
- CAD/Gantry/AB_Drive_Units/a_drive_frame_upper_with_endstop_pinned.step
- CAD/Gantry/AB_Drive_Units/a_drive_frame_upper_with_endstop.step
description: This mod relocates the Y endstop to the top A drive piece
images:
- Images/1.png
- Images/4.png
- Images/2.png
- Images/3.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/Gantry/AB_Drive_Units/a_drive_frame_upper_with_jst_y_endstop.stl
- STLs/Gantry/AB_Drive_Units/OLD(24r1)/a_drive_frame_upper_with_jst_y_endstop.stl
title: Voron2.4 Y Endstop Relocation
