cad:
- CAD/cover_duct_208.f3d
- CAD/reinforced_duct_208_hole.f3d
- CAD/reinforced_duct_208_no_hole.step
- CAD/reinforced_duct_208_hole.step
- CAD/reinforced_duct_208_no_hole.f3d
- CAD/cover_duct_208.step
description: Mod for a centered cable management
images:
- Pictures/IMG_20220226_094653.jpg
- Pictures/IMG_20220226_094626.jpg
- Pictures/IMG_20220301_163247.jpg
- CAD/Capture1.JPG
- CAD/Capture2.JPG
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/CableDuct_Body_hole_50X208.stl
- STL/CableDuct_Body_no_hole_50X208.stl
- STL/CableDuct_Cover-50X208.stl
title: Center_cable_management_duct
