cad:
- RJ45-Holder.f3d
description: Mount for an ethernet coupler to extend / move the ethernet plug somewhere
  more convenient
images: []
mod_version: 1
printer_compatibility: []
stl:
- RJ45-Mount-a.stl
- RJ45-Mount-b.stl
title: RJ45 Mount
