cad:
- ESP32_bracket.step
description: DIN rail mounting bracket for an ESP32
images:
- esp32_bracket.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- ESP32_Bracket.stl
title: ESP32 DIN Rail Bracket
