cad: []
description: Spool holder that mounts on top for "too close to the wall" printers
images:
- Images/4.png
- Images/5.png
- Images/6.png
- Images/2.png
- Images/3.png
- Images/1.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STL/BB__spool_arm_left.stl
- STL/BB__spool_arm_left__without_panel_pin.stl
- STL/BB__spool_arm_right.stl
- STL/BB__spool_core.stl
- STL/Classic__spool_arm_left.stl
- STL/Classic__spool_arm_left__without_panel_pin.stl
- STL/Classic__spool_arm_right.stl
- STL/Classic__spool_holder.stl
title: V.24/Trident Spool Holder
