cad:
- 12mm_strip_mini_mount.step
- 10mm_strip_mount_full_with_channel.step
- 10mm_strip_mount_full.step
description: Basic LED mounts for 10 and 12mm strips
images:
- Images/lighting.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- 10mm_strip_mount_full.stl
- 10mm_strip_mount_full_with_channel.stl
- 12mm_strip_mini_mount.stl
title: LED Mounts
