cad:
- CAD/canable_pro_clip.f3d
- CAD/canable_pro_clip.step
- CAD/canable_pro_mount.step
- CAD/canable_pro_mount.f3d
description: MKS CANable Pro mount which mounts on a DIN rail
images:
- Images/canable_pro_mount_built.jpg
- Images/canable_pro_mount_parts.jpg
- Images/canable_pro_cad.jpg
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VSW
- VT
stl:
- STLs/canable_pro_clip.stl
- STLs/canable_pro_mount.stl
- STLs/pcb_din_clip.stl
title: MKS CANable Pro DIN Mount
