cad:
- cad/v0_3x3_wago_v2.f3d
- cad/v0_3x3_wago_v2.step
description: Easy to install Wago mounts for v0 mains
images:
- images/mains_wago_v0_1.jpeg
- images/mains_wago_v0_2.jpeg
- images/mains_wago_v0_3.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- stl/v0_3x3_wago_v2.stl
title: v0 Power Wagos
