cad:
- CAD/v0-dc-inlet.step
description: Skirt inlet for external 24V DC power supply.
images:
- Images/assembly1.png
- Images/assembly2.png
- Images/assembly3.png
- Images/wiring.png
- Images/photo.jpg
- Images/render.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/inlet_bracket.stl
- STLs/skirt_rear_left_with_inlet.stl
- STLs/skirt_rear_right.stl
- STLs/skirt_side_with_inlet.stl
title: V0 DC inlet
