cad:
- CAD/270-Hinge-Parametric.step
- CAD/270-Hinge-Parametric.f3d
description: "Hinges that have 270\xB0 of swivel, parametric CAD included"
images:
- Images/installed-0-closed.jpg
- Images/installed-180.jpg
- Images/FacePlate_width.jpg
- Images/parts.jpg
- Images/installed-close.jpg
- Images/installed-270.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/backplate_x4.stl
- STLs/handle_a_x2.stl
- STLs/handle_b_x2.stl
- STLs/tester_4mm.stl
- STLs/tester_5mm.stl
- STLs/tester_6mm.stl
- STLs/3mm_drilled/3mm_hinge_a_without_logo_x2.stl
- STLs/3mm_drilled/3mm_hinge_a_with_logo_x2.stl
- STLs/3mm_drilled/3mm_hinge_b_without_logo_x2.stl
- STLs/3mm_drilled/3mm_hinge_b_with_logo_x2.stl
- STLs/3mm_drilled/3mm_latch_x2.stl
- STLs/3mm_drilled/3mm_side_mount_x4.stl
- STLs/3mm_tape/3mm_hinge_a_without_logo_x2.stl
- STLs/3mm_tape/3mm_hinge_a_with_logo_x2.stl
- STLs/3mm_tape/3mm_hinge_b_without_logo_x2.stl
- STLs/3mm_tape/3mm_hinge_b_with_logo_x2.stl
- STLs/3mm_tape/3mm_latch_x2.stl
- STLs/3mm_tape/3mm_side_mount_x4.stl
- STLs/4mm_drilled/4mm_hinge_a_without_logo_x2.stl
- STLs/4mm_drilled/4mm_hinge_a_with_logo_x2.stl
- STLs/4mm_drilled/4mm_hinge_b_without_logo_x2.stl
- STLs/4mm_drilled/4mm_hinge_b_with_logo_x2.stl
- STLs/4mm_drilled/4mm_latch_x2.stl
- STLs/4mm_drilled/4mm_side_mount_x4.stl
- STLs/4mm_tape/4mm_hinge_a_without_logo_x2.stl
- STLs/4mm_tape/4mm_hinge_a_with_logo_x2.stl
- STLs/4mm_tape/4mm_hinge_b_without_logo_x2.stl
- STLs/4mm_tape/4mm_hinge_b_with_logo_x2.stl
- STLs/4mm_tape/4mm_latch_x2.stl
- STLs/4mm_tape/4mm_side_mount_x4.stl
- STLs/5mm_drilled/5mm_hinge_a_without_logo_x2.stl
- STLs/5mm_drilled/5mm_hinge_a_with_logo_x2.stl
- STLs/5mm_drilled/5mm_hinge_b_without_logo_x2.stl
- STLs/5mm_drilled/5mm_hinge_b_with_logo_x2.stl
- STLs/5mm_drilled/5mm_latch_x2.stl
- STLs/5mm_drilled/5mm_side_mount_x4.stl
- STLs/5mm_tape/5mm_hinge_a_without_logo_x2.stl
- STLs/5mm_tape/5mm_hinge_a_with_logo_x2.stl
- STLs/5mm_tape/5mm_hinge_b_without_logo_x2.stl
- STLs/5mm_tape/5mm_hinge_b_with_logo_x2.stl
- STLs/5mm_tape/5mm_latch_x2.stl
- STLs/5mm_tape/5mm_side_mount_x4.stl
- STLs/6mm_drilled/6mm_hinge_a_without_logo_x2.stl
- STLs/6mm_drilled/6mm_hinge_a_with_logo_x2.stl
- STLs/6mm_drilled/6mm_hinge_b_without_logo_x2.stl
- STLs/6mm_drilled/6mm_hinge_b_with_logo_x2.stl
- STLs/6mm_drilled/6mm_latch_x2.stl
- STLs/6mm_drilled/6mm_side_mount_x4.stl
- STLs/6mm_tape/6mm_hinge_a_without_logo_x2.stl
- STLs/6mm_tape/6mm_hinge_a_with_logo_x2.stl
- STLs/6mm_tape/6mm_hinge_b_without_logo_x2.stl
- STLs/6mm_tape/6mm_hinge_b_with_logo_x2.stl
- STLs/6mm_tape/6mm_latch_x2.stl
- STLs/6mm_tape/6mm_side_mount_x4.stl
title: "270\xB0 Front Panel Hinge"
