cad: []
description: Voron0 MidPanel with Hex pattern and Wire cover
images:
- IMG/V00_1.jpg
- IMG/V00_2.jpg
- IMG/V01_1.jpg
- IMG/V01_2.jpg
- IMG/IMG5.jpg
- IMG/IMG4.jpg
- IMG/IMG3.jpg
- IMG/IMG0.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- V00_MidPanelCover.stl
- V00_MidPanelHex.stl
- V01_MidPanelHex.stl
title: V0 MidPanel HexPattern
