cad: []
description: Exhaust filter housing with the G1-8 "thread on the side.
images:
- efh_s_2.png
- efh_s_1.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- exhaust_filter_housing_side.stl
title: Exhaust filter housing - side thread
