cad: []
description: Connector cover for 42STH20-1004AS
images:
- exodius_afterburner.jpg
- compare.png
mod_version: 1
printer_compatibility:
- VSW
stl:
- STL/Voron_SwitchWire_Connector_cover_LDO-42STH20-1004AS2.stl
title: Afterburner connector cover for 42STH20-1004AS
