cad:
- Dioder_Led_Mount.step
description: A mount for the IKEA Dioder LED strip
images:
- Dioder_Led_Mount_Render_1.png
- Dioder_Led_Mount_Render_3.png
- Dioder_Led_Mount_Render_2.png
- IKEA_Dioder_LED_Strip.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Dioder_Led_Mount.stl
title: IKEA Dioder Led Mount
