cad: []
description: Rail installation guide that also works for the 2.4 dual rail installation
images:
- images/guide.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- dual_rail_installation_guide_center_x2.stl
title: Dual Rail Installation Guide
