cad:
- CAD/Z_Idlers/z_Idler_pinned.step
- CAD/Gantry/V24R2_Gantry_PinsMod.step
- CAD/Gantry/TridentR1_Gantry_PinsMod.step
- CAD/Gantry/Front_Idlers/[a]_tensioner_right_pinned.step
- CAD/Gantry/Front_Idlers/[a]_tensioner_left_pinned.step
- CAD/Gantry/X_Axis/XY_Joints/xy_joint_right_pinned.step
- CAD/Gantry/X_Axis/XY_Joints/xy_joint_left_pinned.step
- CAD/Gantry/AB_Drive_Units/a_drive_frame_upper_pinned.step
- CAD/Gantry/AB_Drive_Units/a_drive_frame_lower_pinned.step
- CAD/Gantry/AB_Drive_Units/b_drive_frame_lower_pinned.step
- CAD/Gantry/AB_Drive_Units/b_drive_frame_upper_pinned.step
description: This mod replaces all the M5 screws for all idlers/pulleys/bearings with
  5mm pins
images:
- Images/2.jpg
- Images/z.jpg
- Images/4.png
- Images/2.png
- Images/3.png
- Images/1.jpg
- Images/ADrive/4.png
- Images/ADrive/2.png
- Images/ADrive/3.png
- Images/ADrive/1.png
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- STLs/Gantry/AB_Drive_Units/Trident/a_drive_frame_lower_pinned.stl
- STLs/Gantry/AB_Drive_Units/Trident/a_drive_frame_upper_pinned.stl
- STLs/Gantry/AB_Drive_Units/Trident/a_drive_frame_upper_with_jst_y_endstop_pinned.stl
- STLs/Gantry/AB_Drive_Units/Trident/b_drive_frame_lower_pinned.stl
- STLs/Gantry/AB_Drive_Units/Trident/b_drive_frame_upper_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/a_drive_frame_lower_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/a_drive_frame_upper_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/a_drive_frame_upper_with_jst_y_endstop_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/b_drive_frame_lower_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/b_drive_frame_upper_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/a_drive_frame_lower_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/a_drive_frame_lower_pinned24r2.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/a_drive_frame_upper_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/a_drive_frame_upper_pinned24r2.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/a_drive_frame_upper_with_jst_y_endstop_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/a_drive_frame_upper_with_jst_y_endstop_pinned24r2.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/b_drive_frame_lower_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/b_drive_frame_lower_pinned24r2.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/b_drive_frame_upper_pinned.stl
- STLs/Gantry/AB_Drive_Units/V2/Old(24r1)/b_drive_frame_upper_pinned24r2.stl
- STLs/Gantry/Front_Idlers/[a]_a_tensioner_pinned.stl
- STLs/Gantry/Front_Idlers/[a]_b_tensioner_pinned.stl
- STLs/Gantry/Front_Idlers/Old(24r1)/[a]_a_tensioner_pinned.stl
- STLs/Gantry/Front_Idlers/Old(24r1)/[a]_a_tensioner_pinned_24r2.stl
- STLs/Gantry/Front_Idlers/Old(24r1)/[a]_b_tensioner_pinned.stl
- STLs/Gantry/Front_Idlers/Old(24r1)/[a]_b_tensioner_pinned_24r2.stl
- STLs/Gantry/X_Axis/XY_Joints/MGN12_xy_joint_left_lower_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/MGN12_xy_joint_left_upper_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/MGN12_xy_joint_right_lower_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/MGN12_xy_joint_right_upper_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_left_lower_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_left_lower_pinned_24r2.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_left_upper_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_left_upper_pinned_24r2.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_right_lower_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_right_lower_pinned_24r2.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_right_lower_pinned_no_wire_path.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_right_upper_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_right_upper_pinned_24r2.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/MGN12_xy_joint_right_upper_pinned_no_wire_path.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/xy_joint_left_lower_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/xy_joint_left_upper_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/xy_joint_right_lower_pinned.stl
- STLs/Gantry/X_Axis/XY_Joints/Old(24r1)/xy_joint_right_upper_pinned.stl
- STLs/Z_Idlers/[a]_z_tensioner_x4_6mm_pinned.stl
- STLs/Z_Idlers/[a]_z_tensioner_x4_9mm_pinned.stl
title: Voron2.4 and Trident Pins Mod
