cad: []
description: HEPA filter chamber exhaust replacement.
images:
- Images/exhaust-fan-assembly.png
- Images/exhaust-chamber-mount-jst-terminal.png
- Images/hepa-chamber-exhaust-cad.png
- Images/exhaust-chamber-mount-back.png
- Images/exhaust-HEPA-filter-insert.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STLs/exhaust-chamber-mount.stl
- STLs/exhaust-hepa-filter-housing.stl
- STLs/exhaust-lid.stl
title: HEPA Exhaust
