cad:
- cad/z-locks.f3d
- cad/z-locks.step
description: Helping hands curing v2.4 build, replaces long zip ties.
images:
- images/z-locks-installed.png
- images/z-locks.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- stls/z-locks-100.stl
- stls/z-locks-150.stl
- stls/z-locks-200.stl
title: Z Locks
