cad: []
description: Raspberry mount vertically in the plug panel, allow easy access to ports
images:
- Images/image0.jpg
- Images/image1.jpg
- Images/image2.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- plug_panel_raspberry_bracket.stl
- plug_panel_with_raspberry_DD11.stl
- plug_panel_with_raspberry_filtered_rocker.stl
- plug_panel_with_raspberry_unfiltered.stl
title: Raspberry in plug panel
