cad: []
description: Modified MiniSB to use a Sharkfin Extruder
images:
- Images/Sharkfin1.png
- Images/Sharkfin2.png
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VSW
- VT
stl:
- STL/Sharkfin_MiniSB_cowling.stl
title: MiniSB_Sharkfin
