cad:
- CAD/ADXL345-Carriage-GY-291-v3.f3d
- CAD/ADXL345-Carriage-Adafruit-v45.f3d
description: Permanent mount for ADXL boards on the back of the motor, replacing the
  drag chain mount.
images:
- Images/CAD-Adafruit.png
- Images/TheDamage.jpg
- Images/Clearance.jpg
- Images/CAD.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/ChainAnchor-Generic-ADXL345-Adafruit.stl
- STL/ChainAnchor-Generic-ADXL345-GY-291.stl
- STL/ChainAnchor-IGUS-ADXL345-Adafruit.stl
- STL/ChainAnchor-IGUS-ADXL345-GY-291.stl
title: ADXL drag chain mount
