cad: []
description: Kirigami bed front with space for a single LED or Neopixel button
images:
- Bedfront.jpg
- Beddefuser2.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Kirigami_Bed_LED_Diffuser_.stl
- Kirigami_Bed_LED_Front.stl
title: Kirigami LED Bed Front
