cad:
- CAD/RefillPlease_v20.f3d
description: Replace the 2.4 stock bowden tube holder and add a filament runout sensor
images:
- images/interior90.png
- images/refillplease.png
- images/lever.png
- images/Overview.png
- images/notch.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STLs/cover_left.stl
- STLs/cover_right.stl
- STLs/[a]_core_left.stl
- STLs/[a]_core_right.stl
title: V2.4 Filament runout sensor
