cad: []
description: Voron 0.1 Power inlet with keystone insert slot
images:
- images/installed.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/Power_Inlet_w_Keystone_Insert_x1.stl
title: Power Inlet with Keystone Insert
