cad:
- CAD/stealth_bumper.step
description: an RGB-Powered front-bed mount for the Voron V0 with Kirigami Bed Frame
discord_username: mapleleafmakers
images:
- Images/photo.jpg
- Images/render.png
mod_version: 1
printer_compatibility:
- V0
stl:
- STL/logo_insert.stl
- STL/neopixel_button_carrier.stl
- STL/rainbow_barf_carrier.stl
- STL/[a]_main_body.stl
- STL/[c]_neopixel_button_diffuser.stl
- STL/[c]_rainbow_barf_diffuser.stl
title: Kirigami Stealth Bumper
