cad: []
description: Fly-Gemini adapted model for V0
images: []
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Bracket/Gemini_v0.1_Stent_FLYLOGO.STL
- Bracket/Gemini_v0.1_Stent_MellowLOGO.STL
title: V0 Fly-Gemini
