cad: []
description: Mod to mount a Waveshare 5.5inch full HD display on a V2
images:
- Images/photo.jpeg
- Images/fusion-back.png
- Images/fusion-front.png
mod_version: 1
printer_compatibility:
- V2.4
- VSW
stl:
- STLs/Voron-2.4-Mount-Generisch-v6.stl
- STLs/WaveShare-5.5-cover.stl
title: Waveshare 5.5inch HDMI AMOLED Mount
