cad:
- CAD/Mantis_MGN12_CrazyVolcano_v1.0.step
- CAD/Mantis_MGN12_Dragon_v1.041_and_v1.043e.step
- CAD/Mantis_MGN12_Rapido_and_Rapido_UHF.step
- CAD/Mantis_MGN9_v1.0a.step
description: MGN12 Dual 5015 Toolhead for 2.4 & 1.8
images:
- images/readme_mantis.jpg
- images/readme_cfd_crazy_volcano.png
- images/carriage_assembly_mgn9_front.jpg
- images/carriage_assembly_crazy_volcano.jpg
- images/final_assembly_duct_brace.jpg
- images/final_assembly_adxl_front.jpg
- images/readme_cfd_dragon.png
- images/1.8_koonweee_thumb.png
- images/final_assembly_rapido.jpg
- images/hotends_rapdio_cad.png
- images/carriage_assembly_solder_magnet.jpg
- images/carriage_assembly_carriage_bottom.jpg
- images/magprobe_bed_mount.jpg
- images/carriage_assembly_mgn9_rear_wiring.jpg
- images/print_orientation_slicer.png
- images/final_assembly_crazy_volcano_rear.jpg
- images/readme_cfd_rapido.png
- images/magprobe_solder_switch.jpg
- images/carriage_assembly_sherpa_brace_mounted_side.jpg
- images/final_assembly_adxl_carriage.jpg
- images/carriage_assembly_hotend_mount_front.jpg
- images/final_assembly_top.jpg
- images/magprobe_gantry_mount_side.jpg
- images/carriage_assembly_hotend_mount_top.jpg
- images/carriage_assembly_rapido.jpg
- images/carriage_assembly_sherpa_brace_hotend_mount.jpg
- images/final_assembly_heater_back.jpg
- images/carriage_assembly_mgn9_front_mounted.jpg
- images/final_assembly_crazy_volcano.jpg
- images/magprobe_gantry_mount_front.jpg
- images/print_orientation_ducts.jpg
- images/carriage_assembly_sherpa_brace_mounted_front.jpg
- images/carriage_assembly_mgn12_front.jpg
- images/readme_exploded.png
- images/magprobe_bed_mount_front.jpg
- images/firmware_slicer_cooling_settings.png
- images/1.8_OscarGM_cut_ears.jpg
- images/carriage_assembly_heatsets.jpg
- images/1.8_koonweee.png
- images/magprobe_bed_mount_rear.jpg
- images/print_orientation_keep_only_bridges.png
- images/magprobe_assembled.jpg
- images/print_orientation_duct_divider.jpg
- images/carriage_assembly_mgn12_rear.jpg
- images/carriage_assembly_mgn9_rear_belts.jpg
- images/magprobe_attached_to_carriage.jpg
- STLs/Duct_Brace/Images/Duct_Brace_Simple.png
- STLs/Duct_Brace/Images/Duct_Brace_Full.png
- STLs/Duct_Brace/Images/Duct_Brace_Back.jpg
- STLs/Duct_Brace/Images/Duct_Brace_Full_Hardware.png
- STLs/Duct_Brace/Images/Duct_Brace_OpenVsClosed.jpg
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
stl:
- STLs/Carriage_MGN12_v1.040.stl
- STLs/Carriage_MGN9_v1.0.stl
- STLs/Chain_Anchor_v3.1_IGUS.stl
- STLs/Chain_Anchor_v3.2.stl
- STLs/Hotend_Mount_Dragon_v1.040.stl
- STLs/Hotend_Mount_Dragon_v1.040_sherpa_brace.stl
- STLs/Hotend_Mount_Rapido_v.03.stl
- STLs/Hotend_Mount_Rapido_v.03_Rotated120Degrees.stl
- STLs/Umbilical_Mount_v2.stl
- STLs/Ducts/1.8/Duct_v1.037_Left_+2mm.stl
- STLs/Ducts/1.8/Duct_v1.037_Right_+2mm.stl
- STLs/Ducts/2.4/duct_dragon_crazy_volcano_v1.0_left.stl
- STLs/Ducts/2.4/duct_dragon_crazy_volcano_v1.0_right.stl
- STLs/Ducts/2.4/duct_dragon_v1.041_Left.stl
- STLs/Ducts/2.4/duct_dragon_v1.041_Right.stl
- STLs/Ducts/2.4/duct_dragon_v1.043e_Left.stl
- STLs/Ducts/2.4/duct_dragon_v1.043e_Right.stl
- STLs/Ducts/2.4/duct_rapido_HF_v0.03b_left.stl
- STLs/Ducts/2.4/duct_rapido_HF_v0.03b_right.stl
- STLs/Ducts/2.4/duct_rapido_UHF_v0.03b_left.stl
- STLs/Ducts/2.4/duct_rapido_UHF_v0.03b_right.stl
- STLs/Duct_Brace/Duct_Brace_Simple_v1.0.stl
- STLs/Duct_Brace/Full_Brace/Dragon/Duct_Brace_Dragon_Clamp_Left_v1.0.stl
- STLs/Duct_Brace/Full_Brace/Dragon/Duct_Brace_Dragon_Clamp_Right_v1.0.stl
- STLs/Duct_Brace/Full_Brace/Dragon/Duct_Brace_Dragon_Full_v1.2_Closed_mount.stl
- STLs/Duct_Brace/Full_Brace/Dragon/Duct_Brace_Dragon_Full_v1.2_Open_mount.stl
- STLs/Duct_Brace/Full_Brace/Rapido_Crazy_Volcano/Duct_Brace_Rapido_Crazy_Volcano_Clamp_Left_v1.1.stl
- STLs/Duct_Brace/Full_Brace/Rapido_Crazy_Volcano/Duct_Brace_Rapido_Crazy_Volcano_Clamp_Right_v1.1.stl
- STLs/Duct_Brace/Full_Brace/Rapido_Crazy_Volcano/Duct_Brace_Rapido_Crazy_Volcano_Full_v1.2_Closed_Mount.stl
- STLs/Duct_Brace/Full_Brace/Rapido_Crazy_Volcano/Duct_Brace_Rapido_Crazy_Volcano_Full_v1.2_Open_Mount.stl
- STLs/Magprobe/Magprobe_v0.31_Dragon.stl
- STLs/Magprobe/Magprobe_v0.31_RapidoHF_and_CrazyVolcano.stl
- STLs/Magprobe/Magprobe_v0.31_RapidoUHF.stl
- STLs/Magprobe/Bed_Extrusion_Mount/Magprobe_Dock_Arms_v1.5.stl
- STLs/Magprobe/Bed_Extrusion_Mount/Magprobe_Dock_Mount_v1.0.stl
- STLs/Magprobe/Gantry_Mount/Magprobe_Gantry_Dock_Arm_v1.5_double_magnet.stl
- STLs/Magprobe/Gantry_Mount/Magprobe_Gantry_Dock_Arm_v1.5_Single_magnet.stl
- STLs/Magprobe/Gantry_Mount/Magprobe_Gantry_Dock_Mount_by_JosAr_v1.stl
- STLs/Magprobe/Gantry_Mount/Magprobe_Gantry_Extrusion_Mount_by_JosAr_v1.stl
title: Mantis Dual 5015 Toolhead
