cad: []
description: Corner panel clip that fit 3mm or 1/8" panels with foam tape
images: []
mod_version: 1
printer_compatibility:
- V2.1
- V2.2
stl:
- corner_panel_clip_0.125in_version_x12.stl
title: Corner Panel Clip
