cad:
- CAD/Short_Z_Joints.step
description: Shorter Z joints for the v2.4
images:
- Images/Side-By-Side.png
- Images/Side-By-Side-Cross-Section.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/Z_Bearing_Block_Bottom.stl
- STL/Z_Bearing_Block_Top.stl
- STL/Z_Belt_Clamp_Lower.stl
title: Short Z Joints
