cad: []
description: Mounts for Big Tree Tech Smart Filament Motion Sensor
images:
- IMG_2384.png
- SKR_2.png
- SKRV1_4.png
- Mount_B.png
- Mount_A.png
- IMG_2385.png
- BTT_Sensor.png
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VSW
stl:
- BTT_Sensor_Mount_A.stl
- BTT_Sensor_Mount_B.stl
title: Mounts for BTT Filament Motion Sensor
