cad:
- rear_bottom_left_bracket_with_stop.step
- rear_bottom_right_bracket_with_stop.step
description: Remixed rear bottom panel mounts with stop
images: []
mod_version: 1
printer_compatibility:
- V0.2
stl:
- rear_bottom_left_bracket_with_stop.stl
- rear_bottom_right_bracket_with_stop.stl
title: Remixed Panel Mounts
