cad:
- Assem1.SLDASM
- Load_Cell.SLDPRT
- Load_Cell.STEP
- Mount.SLDPRT
- Mount.STEP
- Spool_Holder_1mm_Clearance.SLDPRT
- Spool_Holder_1mm_Clearance.STEP
- Spool_Holder_2mm_Clearance.SLDPRT
- Spool_Holder_2mm_Clearance.STEP
description: Spool holder with scale
images: []
mod_version: 1
printer_compatibility:
- V2.1
stl:
- Mount.STL
- Spool_Holder_1mm_Clearance.STL
- Spool_Holder_2mm_Clearance.STL
title: Spool holder with scale
