cad: []
description: V2.4 Duet 3 6HC Din Bracket
images:
- Example_print-courtesy_of_medicusdkfz.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Duet_3_6HC_Bracket.stl
title: Duet 3 6HC Din Bracket
