cad: []
description: Safely capture your bed wires thru the bottom panel
images:
- images/elec_bay_side.jpg
- images/chamber_side.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- grommet_1.stl
- Grommet_2.stl
- Grommet_3.stl
- Grommet_4.stl
title: V2.4 Bed Wiring Grommet
