cad:
- STEP/SkirtPower.step
description: Skirt-mounted rocker switch for easy access for Voron 2.4
images:
- images/SkirtPower-photo.png
- images/SkirtPower.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/side_skirt_switch_250.stl
- STL/side_skirt_switch_300.stl
- STL/side_skirt_switch_350.stl
title: Side Skirt Power Switch
