cad:
- Buttons/CAD.f3d
description: Skirt mod for custom Gcode macro buttons
images:
- Pictures/2.jpg
- Pictures/4.jpg
- Pictures/3.jpg
- Pictures/1.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- 250/250.stl
- 250/250_mirror.stl
- 300/300.stl
- 300/300_mirror.stl
- 350/350.stl
- 350/350_mirror.stl
- Buttons/flm_sw.stl
- Buttons/fw_restart.stl
- Buttons/Home.stl
- Buttons/mesh.stl
- Buttons/Pause.stl
- Buttons/Power.stl
- Buttons/preheat.stl
- Buttons/qgl.stl
- Buttons/resume.stl
- Buttons/Stop.stl
title: V2.4 Skirt Buttons
