cad:
- STEPs/Lock_Body.step
- STEPs/Lock_Pin_A_x2.step
- STEPs/glass_rest.STEP
- STEPs/Lock_Pin_B_x2.step
description: Lock levers and rests for 6mm Tempered glass panels
images:
- Images/Glass.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/glass_rest.STL
- STLs/Lock_Body.stl
- STLs/Lock_Pin_A_x2.stl
- STLs/Lock_Pin_B_x2.stl
title: 6mm Tempered Glass Mod
