cad: []
description: Modified version of Trident RPi bracket to fit the smaller RPi Zero
images:
- image/Rendering.JPG
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VT
stl:
- STL/raspberrypi_zero_bracket.stl
title: Raspberry Pi Zero Bracket
