cad:
- PiCamMount350.f3d
- PiCamMount350.step
- PiZeroMount.f3d
- PiZeroMount.step
description: Pi Zero Camera Mount
images: []
mod_version: 1
printer_compatibility: []
stl:
- PiCamMount350.stl
- PiZeroMount.stl
title: Pi Zero Camera Mount
