cad:
- CAD/Z_Shaft_Assembly_12mm_v8.f3d
- CAD/Z_Shaft_Assembly_12mm_v8.step
description: Add V1.8 option for 12mm Z rods
images:
- Images/12mm_Z_Mod.png
- Images/Top_View.png
- Images/Cross_Section.png
mod_version: 1
printer_compatibility:
- V1.8
stl:
- STLs/z_bearing_block_a_12mm_x2.stl
- STLs/z_bearing_block_b_12mm_x2.stl
- STLs/[a]_z_shaft_retainer_12mm_lower_x4.stl
- STLs/[a]_z_shaft_retainer_12mm_upper_x4.stl
title: V1.8 12mm Z Mod
