cad:
- 1515_SnapIn_ZipTie_Makerbeam.step
- 1515_SnapIn_ZipTie_LDO.step
description: Clippable Ziptie hooks for 1515 extrusions
images:
- images/image01.jpg
- images/image03.jpg
- images/image02.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- 1515_SnapIn_ZipTie_LDO.stl
- 1515_SnapIn_ZipTie_Makerbeam.stl
title: Ziptie Mount
