cad: []
description: Activated charcoal exhaust filter with HEPA that replaces the rear tophat
  panel
images:
- Github_Images/Tophat_Install.jpg
- Github_Images/Front_View.jpg
- Github_Images/Side_View.jpg
- Github_Images/Top_View.jpg
- Github_Images/Exploded_Final_Labeled.jpg
- Github_Images/Asm_Front_View.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Fan_Cover_Left_Hole.stl
- Fan_Cover_Right_Hole.stl
- Middle_Charcoal_Chamber.stl
- Middle_Panel_Grill.stl
- Panel_Left_Side.stl
- Panel_Right_Side.stl
- Roomba_HEPA_Cover.stl
title: Tophat Exhaust Filter V0
