cad:
- CAD/Voron0_Block_and_Tackle_Z_Belt.f3d
- CAD/Voron0_Block_and_Tackle_Z_Belt.step
description: A block & tackle belted Z solution using NEMA14. Ratios from 5:1 to 8:1
  and friction prevent Z drop when powered off.
images:
- Images/Block_and_Tackle_Z_Belt_Render.png
- Images/Block_and_Tackle_Z_Belt_Drawing.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/bed_front_Voron0.1_v1.stl
- STLs/bed_front_Voron0_v1.stl
- STLs/bed_mid_v2.stl
- STLs/bed_rear_v2.stl
- STLs/bottom_bracket_v3.stl
- STLs/motor_bracket_4064_v1.stl
- STLs/pulley_40_v1.stl
- STLs/pulley_48_v2.stl
- STLs/pulley_64_v1.stl
- STLs/tensioner_insert_v1.stl
- STLs/top_bracket_v3.stl
- STLs/[a]_tensioner_v1.stl
title: Voron0 Block & Tackle Z Belt
