cad:
- CAD/Trident_2.4_ComboInletSkirt_v8.f3d
- CAD/Trident_2.4_ComboInletSkirt_v8.step
description: Skirt pieces for Trident, 2.4 and 2.4r2 for combo inlets in 2 sizes.
images:
- ComboInlets.png
- BothInlet.png
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- STLs/2.4r2_ComboNarrowInlet.stl
- STLs/2.4r2_ComboWideInlet.stl
- STLs/2.4_ComboNarrowInlet.stl
- STLs/2.4_ComboWideInlet.stl
- STLs/Trident_ComboNarrowInlet.stl
- STLs/Trident_ComboWideInlet.stl
title: ComboInlet
