cad: []
description: Created a new skirt design that uses 50mm extrusions as legs and it has
  a c14 power inlet hole on the bottom
images:
- Images/1.png
mod_version: 1
printer_compatibility:
- V0.1
stl:
- STL/Leg_End_Cap_x4.stl
- STL/Rear_Skirt_mirror_x1.stl
- STL/Rear_Skirt_x1.stl
- STL/Skirt_x3.stl
title: Voron0 ExtrusionSkirt
