cad: []
description: A easy to install cover for spec 60mm fans originally designed for a
  2.4 build
images:
- Images/FancoverOverview.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/60mm_fan_grill_rev1.stl
title: 60mm Fan Cover
