cad:
- CAD/v0_Hinged_TopHat.step
description: Created a new hinged top hat design for the V0 so it can fold away when
  you dont want a top hat on
images:
- Images/4.jpg
- Images/2.jpg
- Images/3.jpg
- Images/1.jpg
- Images/Assembly/step5.png
- Images/Assembly/step4.png
- Images/Assembly/step6.png
- Images/Assembly/step7.png
- Images/Assembly/step3.png
- Images/Assembly/step2.png
- Images/Assembly/step1.png
- Images/Assembly/FinalAssembly.png
- Images/Assembly/step10.png
- Images/Assembly/step9.png
- Images/Assembly/step8.png
mod_version: 1
printer_compatibility:
- V0.1
stl:
- STL/Bottom_Hinge_x2.stl
- STL/Middle_Hinge_x2.stl
- STL/TopHat_Alignment_Pin_x2.stl
- STL/TopHat_hole_Drilling_Guide_x1.stl
- STL/TopHat_Rear_Outer_Panel_x1.stl
- STL/Top_Hinge_Mirror_x1.stl
- STL/Top_Hinge_x1.stl
- STL/[a]_Hinge_Stop_With_Back_Panel_Mirror_x1(2.5mm).stl
- STL/[a]_Hinge_Stop_With_Back_Panel_Mirror_x1(2mm).stl
- STL/[a]_Hinge_Stop_With_Back_Panel_Mirror_x1(3mm).stl
- STL/[a]_Hinge_Stop_With_Back_Panel_x1(2.5mm).stl
- STL/[a]_Hinge_Stop_With_Back_Panel_x1(2mm).stl
- STL/[a]_Hinge_Stop_With_Back_Panel_x1(3mm).stl
- STL/[a]_Hinge_Stop_With_No_Back_Panel_x2.stl
- STL/[a]_Hinge_Stop_x2.stl
title: Voron0 Hinged Top Hat
