cad: []
description: Bracket for Raspberry pi zero.
images:
- rbp_bracket_front.png
- rbp_bracket_back.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
stl:
- rbp_zero_bracket.stl
title: RBP Zero Bracket
