cad: []
description: A simple filament runout sensor
images:
- images/front.jpeg
- images/in_use.jpeg
- images/inside.jpeg
- images/back.jpeg
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VSW
stl:
- back.stl
- front.stl
- spinner.stl
title: Filament Runout Sensor
