cad:
- STEP/V0_1_Back_Panel_v7.step
description: Vented 2 piece back panel for V0
images:
- Images/PXL_20220621_145343681.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/Back_Panel_Lower.stl
- STL/Back_Panel_Upper.stl
title: V0.1 Two Piece Back Panel
