cad: []
description: Mosfet Mount for 4 or 6 Mosfets
images:
- mosfet.jpg
- mosfet2.png
mod_version: 1
printer_compatibility:
- V1.6
- V2.1
- V2.2
stl:
- Mosfet_Mount_4.stl
- Mosfet_Mount_6.stl
title: Mosfet Mounts
