cad: []
description: Squash Ball Feet for V2.4
images:
- 01-Normal/Panzerballs.png
- 02-Optional_z-Drive-Mod/Panzerball_zDrive_Mod.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- 01-Normal/[a]_PanzerBall_x4.stl
- 02-Optional_z-Drive-Mod/[a]_PanzerBall_Tensioner_Type1_x2.stl
- 02-Optional_z-Drive-Mod/[a]_PanzerBall_Tensioner_Type2_x2.stl
title: PanzerBalls 2.4
