cad: []
description: Useful information and models for using the Bondtech LGX extruder wth
  Afterburner
images:
- images/lever_cover.jpg
- images/cable_cover.jpg
- images/mgn12-rear.jpg
- images/gear_cover.jpg
- images/wires.jpg
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl:
- STLs/30mm-screws/30mm-lgx-blower-housing-rear.stl
- STLs/30mm-screws/30mm-lgx-mount-front.stl
- STLs/extras/lgx-cable-cover.stl
- STLs/extras/lgx-gear-cover.stl
- STLs/extras/lgx-lever-cover.stl
- STLs/mgn12/lgx-mgn12-mount-rear.stl
title: LGX Info, Links, and Models
