cad:
- CAD/led_mount_clippable.step
description: LED Case light for the V0 that clips into the extrusions
images:
- images/printer_installed.jpg
- images/slicer_brim.jpg
- images/cob_led.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/led_mount_clippable.stl
- STL/led_mount_clippable_mirrored.stl
title: V0 Clippable LED Caselight
