cad:
- CAD/Rainbow_Serial_Bumper.step
- CAD/Rainbow_Serial_Bumper.f3d
description: Just a little bit of extra bling for your Voron Trident
discord_username: mapleleafmakers
images:
- Images/[a]_main_body.gif
- Images/[a]_main_body_slicer.png
- Images/[o]_back_plate_slicer.png
- Images/[o]_insert_collar.gif
- Images/[o]_insert_collar_slicer.png
- Images/[oc]_insert_slicer_1.png
- Images/[oc]_insert_slicer_2.png
- Images/[oc]_insert_slicer_3.png
- Images/[oc]_insert_slicer_4.png
- Images/[oc]_insert_slicer_5.png
- Images/assembly_1.gif
- Images/assembly_2.gif
- Images/install.gif
- Images/tridentbling.gif
mod_version: 1
printer_compatibility:
- VT
stl:
- STL/[a]_main_body.stl
- STL/[oc]_insert.stl
- STL/[o]_back_plate.stl
- STL/[o]_insert_collar.stl
title: Rainbow Serial Bumper
