cad:
- V0_reverse_bowden_mount.step
- V0_reverse_bowden_mount.f3d
description: V0 reverse bowden mount
images:
- mount.jpg
- mount_and_filament.jpg
- mount_filament_centered.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- V0_Reverse_Bowden_Mount.stl
title: V0 Reverse Bowden Mount
