cad:
- Z_Motor_Mount_B.f3d
- Z_Motor_Mount_A.f3d
description: Z drive motor mount bracket mod to improve pulley to belt alignment
images:
- Small_key.JPG
- Long_key.JPG
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Z_Motor_Mount_A.stl
- Z_Motor_Mount_B.stl
title: Simplified Z Drive Motor Mount
