cad:
- Trident_r2_Inverted_Electronics_v3.f3d
- Trident_r2_Inverted_Electronics_v3.step
description: Flip the Trident electronics bay for top access.
images:
- InvertedElectronics.png
- BottomPlateInstall.gif
mod_version: 1
printer_compatibility:
- VT
stl:
- STLs/Inverted_DIN_Mount(Mirror)_x2.stl
- STLs/Inverted_DIN_Mount_x2.stl
- STLs/Z_Motor_Mount_Small_Left.stl
- STLs/Z_Motor_Mount_Small_Rear.stl
- STLs/Z_Motor_Mount_Small_Right.stl
title: Trident Inverted Electronics
