cad:
- CAD/Stealthburner-PCBCover-AirVents.step
description: Cable cover for LGX and stealthburner
images:
- Images/LGX_Stealthburner_connectorCover.png
- Images/Preview-front.png
- Images/Preview-back.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl:
- STL/[a]_lgx_stealthburner_pcb_cover_set.stl
title: LGX stealthburner connector cover
