cad:
- CAD/Voron_V2.4_Z_Chain_Guide_Thermistor_Mount.step
description: Modifies the Z chain guide to hold a chamber thermistor
images:
- images/render1.png
- images/render2.png
- images/max-z.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/Z_Chain_Guide_Thermistor_Mount.stl
title: V2.4 Z Chain Guide with Integrated Chamber Thermistor Mount
