cad:
- CAD/esp8266_nodemcu_din_mount_universal.step
description: Din mount for ESP8266 NodeMCU
images:
- Images/esp8266_nodemcu_din_mount.png
- Images/esp8266_nodemcu_din_mount_2.png
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- STLs/esp8266_nodemcu_din_mount_universal.stl
title: ESP8266 NodeMCU Din Mount
