cad:
- Front_Door_Mod.f3d
description: Voron 2.4 door hinges for 3mm panel, 180 deg opening and m3 screw as
  shaft
images:
- door_hinge_new.png
- Assembly.png
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- hinge_left_x2.stl
- hinge_mount_x4.stl
- hinge_right_x2.stl
- latch_x2.stl
title: V2.4 Door Hinge M3 3mm 180deg
