cad:
- CAD/V0.2_Handle.step
description: Add handles to the extrusion tophat
images:
- Images/Handle_1.jpeg
- Images/Handle_2.png
- Images/Handle_3.png
- Images/2.png
- Images/3.png
- Images/1.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/V0.2_Handle_Part_A_x2.stl
- STL/V0.2_Handle_Part_B_x2.stl
- STL/[a]_V0.2_Handle_Logo_Insert_x2.stl
title: V0.2 Handles
