cad:
- Deck_Panel_Backpack.f3d
- Deck_Panel_Backpack.step
description: A mounting alternative if you don't want to drill your deck panel
images:
- images/image02.jpg
- images/image01.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Deck_Panel_Backpack.stl
title: Deck Panel Backpack
