cad:
- steps/fan_mount.step
- steps/gumby_mount_mosquito.step
description: Open toolhead mounting plans for Bondtech BMG-m and Mosquito direct drive
  combo
images: []
mod_version: 1
printer_compatibility:
- V2.1
- V2.2
stl:
- fan_mount.stl
- gumby_mount_mosquito.stl
- gumby_mount_v6.stl
title: Direct Drive BMG-m mount
