cad: []
description: Tools and procedure to properly align the rails in 2.4 and Afterburner
images:
- pivot_front.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Dial_indicator_AB_beta.stl
- Rail_adjust_body.stl
title: Rail Alignment
