cad:
- Tension_Meter.f3d
description: Print in place tension meter to easily tighten multiple belts to the
  same tension
images:
- pictures/installed.png
- pictures/model.png
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VSW
stl:
- TensionMeter.stl
title: Belt Tension Meter
