cad:
- CAD/HorseshoeSpoolHolder_v10.f3d
- CAD/HorseshoeSpoolHolder_v10.step
description: Horseshoe Spool Holder - mounts internally for Trident, or externally
  for V0, V1, or V2 printers.
images:
- TIS.png
- ES.png
- PB.png
- TI.jpg
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VT
stl:
- STLs/608BearingRing(6x).stl
- STLs/ExternalSpoolHolder.stl
- STLs/PlasticBolt(x3).stl
- STLs/ShortPlasticBolt(3x).stl
- STLs/Trident_InternalSpoolHolder.stl
title: HorseshoeSpoolHolder
