cad:
- CAD/Stealthburner_Printhead_Crazy_Dragon.step
description: The Stealthburner toolhead mount for Mellow Crazy, TriangleLab T-Volcano
  and Phaetus UHF mini
images:
- front.png
- bottom.PNG
- cut_section.PNG
- back.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl:
- STL/SBCrazyDragon_TH_Front.stl
- STL/SBCrazyDragon_TH_Rear_CW2.stl
title: Stealthburner (RC1) Dragon Volcano Hotend Toolhead Mount
