cad: []
description: Support for the coroplast to prevent sagging
images: []
mod_version: 1
printer_compatibility:
- V2.1
stl:
- coroplast_support_lower.stl
- coroplast_support_upper.stl
title: Coroplast Support
