cad:
- Probeholder_M12.step
description: Drop in replacement of the stock probe to a M12
images:
- M12_probe_mount.jpg
mod_version: 1
printer_compatibility:
- V2.1
stl:
- M12_probe_mount.stl
title: M12 Probeholder
