cad:
- cad/300LeadScrewMount.step
- cad/250LeadScrewBlock.step
- cad/ZMotorMount.step
description: Add MGN12H linear rails for Z axis motion
images:
- isoview1.png
mod_version: 1
printer_compatibility:
- V1.8
stl:
- stl/250LeadScrewBlock.stl
- stl/300LeadScrewBlock.stl
- stl/ZMotorMount.stl
title: V1.8 Z Rails Mod
