cad: []
description: Adapter to use a metal DIN mount for the BTT 24V UPS
images:
- BTT_UPS_24V_DIN.jpeg
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
stl:
- BTT_UPS_24V_DIN.stl
title: BTT 24V UPS Metal DIN Mount
