cad:
- thermistor_holder_zero.step
description: Extended thermistor holder for Voron Zero
images:
- installed.png
- thermistor_holder_comparison.png
mod_version: 1
printer_compatibility:
- V0.2
- VSW
- VT
stl:
- thermistor_holder_zero.stl
title: Thermistor holder zero
