cad:
- CAD/[a]_top_corner_cable_hide_x4.step
description: Mod to hide cables around z idlers
images:
- Images/[a]_top_corner_cable_hide_back.png
- Images/[a]_top_corner_cable_hide_inside.png
- Images/[a]_top_corner_cable_hide.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/[a]_top_corner_cable_hide_left_x2.stl
- STLs/[a]_top_corner_cable_hide_right_x2.stl
title: Corner Cable Hide/Cover (LED Wires)
