cad: []
description: Voron Exhaust Filter Inserts for Activated Coal + Hepa
images:
- Images/CAD1.png
- Images/VEFACH.png
- Images/4.jpg
- Images/5.jpg
- Images/CAD4.png
- Images/6.jpg
- Images/2.jpg
- Images/Trident_V2.png
- Images/3.jpg
- Images/1.jpg
- Images/CAD3.png
- Images/CAD2.png
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- STL_CAD/V2.4(R1)/0_filterdummy_dont_print.stl
- STL_CAD/V2.4(R1)/1_coal_for_infill_mesh.stl
- STL_CAD/V2.4(R1)/1_coal_with_mesh.stl
- STL_CAD/V2.4(R1)/1_hepa.stl
- STL_CAD/V2.4(R1)/1_lid.stl
- STL_CAD/V2.4(R2)_Trident/0_filterdummy_dont_print.stl
- STL_CAD/V2.4(R2)_Trident/1_coal_for_infill_mesh.stl
- STL_CAD/V2.4(R2)_Trident/1_coal_with_mesh.stl
- STL_CAD/V2.4(R2)_Trident/1_hepa.stl
- STL_CAD/V2.4(R2)_Trident/1_lid.stl
title: VEFACH
