cad:
- STEP/Stealthburner_Printhead_Crazy_Mozzie.step
description: Toolhead for Crazy Mozzie HF, compatible with Stealthburner and Clockwork
  2
images:
- images/pic.jpg
- images/pic2.jpg
- images/render.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl:
- STL/SB_MQT_TH_Front.stl
- STL/SB_MQT_TH_Rear_CW2.stl
title: Crazy Mozzie HF toolhead SB+CW2
