cad:
- CAD/Trident_dual_power_switch.step
- CAD/Trident_dual_power_switch.f3d
description: A replacement skirt, allowing 2 power switches
images:
- Images/DualSwitch.jpg
mod_version: 1
printer_compatibility:
- VT
stl:
- STLs/power_inlet_filtered.stl
title: Trident Dual Power Switch
