cad: []
description: Filtered Power Plug for RND 165-00057 and CAT6-Plug
images: []
mod_version: 1
printer_compatibility:
- V2.4
stl:
- mains_plug_panel_filtered_for_RND_165-00057_V24.stl
title: Filtered Power Plug with RND_165-00057
