cad:
- Elevator Switch Skirt holder v4.f3d
description: Holder for Anit-Vandal Switches mounted in skirt holes
images:
- Switchpreview.jpg
mod_version: 1
printer_compatibility:
- V2.1
- V2.2
stl:
- 19mm_Switch_Holder_BACK.stl
- 19mm_Switch_Holder_FRONT.stl
title: Switch Holder
