cad:
- mount.f3d
- mount.step
description: A mount PL05 inductive sensor
images:
- probe.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- left_duct.stl
- pl05_holder.stl
- right_duct.stl
title: PL05 Sensor Mount
