cad:
- CAD/LoudOwl_v16.f3d
- CAD/LoudOwl_v16.step
- CAD/LoudOwl_for_split_ABBN_untested.step
description: Alternative dual 5015 part cooling fan toolhead for Afterburner
images:
- Visual/LoudOwl_2.jpg
- Visual/Supp_removal.jpg
- Visual/LoudOWL.jpg
- Visual/Wiring.jpg
- Visual/comparison.jpg
- Visual/Fans_in_place.jpg
- Visual/Using_cut_tool_3.jpg
- Visual/Using_cut_tool_2.jpg
- Visual/Using_cut_tool_1.jpg
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
stl:
- STL/Back.stl
- STL/Cut_tool.stl
- STL/Front_piece_w_supports.stl
- STL/Logo_piece_w_support.stl
- STL/without_in_build_supports/Back_piece.stl
- STL/without_in_build_supports/Front_piece.stl
- STL/without_in_build_supports/Logo_piece.stl
title: LoudOwl aka Stabby
