cad:
- CAD/V0.1_belted_z_drive.step
- CAD/v0.1_belted_z_kirigami.step
description: Conversion to a belted Z axis for the V0.1 adapted from theFPVGeek's
  mod for the V0.0
images:
- Images/ZBelt-ISO-01.PNG
- Images/ZBelt-ISO-03.PNG
- Images/ZBelt-ISO-02.PNG
- Images/m3nut_check_1.PNG
- Images/ZBelt-ISO-04.PNG
- Images/m3nut_check_2.PNG
- Images/ZBelt-Support-01.png
- Images/mid_panel.JPG
- Images/belt-tight.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/M4_80T_Gear.stl
- STL/Printed-PulleySpacer-x2.stl
- STL/V0-zbelt-BEDMOUNT_MODIFIED_V0.1.stl
- STL/V0-ZBelt-BeltClip-Bottom_MODIFIED_V0.1.stl
- STL/V0-ZBelt-BeltClip-Top_MODIFIED_V0.1.stl
- STL/V0-ZBelt-Deck-Panel-Rear.stl
- STL/V0-ZBelt-FrontBottom-Bracket.stl
- STL/V0-ZBelt-Pancake-Stepper-Bracket.stl
- STL/V0-ZBelt-Top-Idler-Back.stl
- STL/V0-ZBelt-Top-Idler-Front.stl
- STL/Kirigami_Bed_Mount/V0-ZBelt-KirigamiBed_belt_mount.stl
- STL/Kirigami_Bed_Mount/V0-ZBelt-KirigamiBed_body.stl
- STL/Kirigami_Bed_Mount/V0-ZBelt-KirigamiBed_bottom_belt_clamp.stl
- STL/Kirigami_Bed_Mount/V0-ZBelt-KirigamiBed_top_belt_clamp.stl
title: V0.1 Belted Z Drive
