cad: []
description: "mounting for Neopixel strip with 8 LED\xB4s"
images:
- Images/1.jpg
- Images/2.jpg
- Images/3.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/Neopixel_Cover_left.stl
- STLs/Neopixel_Cover_right.stl
- STLs/Neopixel_Mainbody_left.stl
- STLs/Neopixel_Mainbody_right.stl
title: Neopixel Case
