cad: []
description: Tool used for grinding flats on a shaft at specific places
images: []
mod_version: 1
printer_compatibility:
- V1.6
- V2.1
- V2.2
stl:
- mobius_shaft_jig.stl
title: Mobius Shaft Jig
