cad: []
description: Dual mounts for side by side SKR 1.3 controllers with fan and fanless
  options
images:
- Dual_40mm_bed.jpg
- Dual_40mm_Installed.jpg
- Dual_SKR_1.3_Mount.png
- Dual_SKR_1.3_Mount_40mm_fans.png
- Dual_SKR_1.3_Mount_40mm_fans_Topless.png
- Fanless_Installed.jpg
mod_version: 1
printer_compatibility:
- V2.1
- V2.2
stl:
- Dual_SKR_1.3_Mount.stl
- Dual_SKR_1.3_Mount_40mm_fans.stl
- Dual_SKR_1.3_Mount_40mm_fans_Topless_.stl
title: Dual SKR 1.3 Mounts
