cad: []
description: Based on the stock holder but mounts to the horizontal extrusions.
images:
- img/Holder-with-spool.jpg
- img/Holder.png
- img/Holder_1.png
- img/Holder-Real.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Holder.stl
title: Horizontal Spool Holder
