cad:
- CAD/display_middle_skirt.step
- CAD/PiTFT70_Assembly_with_Housing.step
- CAD/display_mount.step
description: Mount for the BTT PiTFT Touchscreen
images:
- images/PiTFT_Render.png
- images/FFC-Routing.jpg
- images/Display_Front.jpg
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- STL/display_middle_skirt.stl
- STL/pitft70_housing_front.stl
- STL/pitft70_housing_rear.stl
- STL/[a]_display_mount_x2.stl
title: PiTFT Mount
