cad:
- CAD/rear_skirt_filtered_mains_keystone.step
- CAD/rear_skirt_filtered_mains_keystone.f3d
- CAD/plug_panel_filtered_mains_keystone.f3d
- CAD/plug_panel_filtered_mains_keystone.step
description: Add a keystone jack to your filtered mains plug panel
images:
- Images/rear.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/Plug_Panel_Filtered_mains_keystone.stl
- STL/rear_skirt_fmks_a_250.stl
- STL/rear_skirt_fmks_a_300.stl
- STL/rear_skirt_fmks_a_320.stl
- STL/rear_skirt_fmks_a_350.stl
- STL/rear_skirt_fmks_b_250.stl
- STL/rear_skirt_fmks_b_300.stl
- STL/rear_skirt_fmks_b_320.stl
- STL/rear_skirt_fmks_b_350.stl
- STL/[a]_keystone_blank_insert.stl
title: Keystone Jack for Filtered Mains Panel
