cad:
- CAD/Handle_Mini_Backdoor.step
- CAD/Back_Door.step
- CAD/Door_Latch_x2.step
description: Door for easy hardware access
images:
- Images/1.jpg
- Images/2.jpg
- Images/3.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/Back_Door.stl
- STLs/Handle_Mini_Backdoor.stl
title: Back Door
