cad:
- WAGO_221-412_5x2-mount.step
- WAGO_221-412_3x2-mount_screw.step
- WAGO_221-412_3x2-mount.step
- WAGO_221-413_3x3-mount-screw.step
- 1515_SnapIn_Makerbeam.step
- 1515_SnapIn_LDO.step
description: Mounts for Wago 221 to screw or clip-in on 1515 extrusions
images:
- images/ScrewMountUsage.jpg
- images/PrintOrientation.jpg
- images/picSnapMount3piece.jpg
- images/Mounting.jpg
- images/picSnapMount5piece.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- 1515_SnapIn_LDO.stl
- 1515_SnapIn_Makerbeam.stl
- WAGO_221-412_3x2-mount.stl
- WAGO_221-412_3x2-mount_screw.stl
- WAGO_221-412_5x2-mount.stl
- WAGO_221-413_3x3-mount-screw.stl
title: Clippable Wago 221 Mounts
