cad:
- CAD/y_tension.f3d
description: Y Tension Mod
images:
- IMAGES/installed.jpg
- IMAGES/parts.jpg
- IMAGES/assembled.jpg
- IMAGES/stack.jpg
mod_version: 1
printer_compatibility:
- VSW
stl:
- STL/HEATSET.stl
- STL/hexnut.stl
- STL/insert.stl
- STL/shell.stl
title: Ender 3 Switchwire Y Tensioner Mod
