cad: []
description: Strain Relief with 10 pin Microfit connector
images:
- Images/pic1.JPG
- Images/pic3.JPG
- Images/pic2.JPG
- Images/remove.JPG
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Strain_Relief_Body_MF10_x1.stl
title: Strain Relief w/ 10 Pin Microfit
