cad:
- cad/NoDropNut_15mm.step
- cad/NoDropNut_Door_Latch_x2.step
- cad/NoDropNut_Rear_Ext_Rear_Edge_x2.step
- cad/NoDropNut_Side_Ext_Side_x2.step
- cad/NoDropNut_12mm.step
- cad/NoDropNut_Rear_Ext_Rear_Center_x1.step
- cad/NoDropNut_Rear_Ext_Front_x2.step
description: Voron0 nut inserts which auto-align (LDO frames only)
images:
- images/z_inside_corner.jpg
- images/sliced.png
- images/z_rear.jpg
- images/z_drive_all.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- stl/NoDropNut_12mm.stl
- stl/NoDropNut_15mm.stl
- stl/NoDropNut_Door_Latch_x2.stl
- stl/NoDropNut_Rear_Ext_Front_x2.stl
- stl/NoDropNut_Rear_Ext_Rear_Center_x1.stl
- stl/NoDropNut_Rear_Ext_Rear_Edge_x2.stl
- stl/NoDropNut_Side_Ext_Side_x2.stl
title: V0 No-Drop Nuts
