cad: []
description: A better supported Spool Holder that mounts to a modified corner panel.
images:
- IMG/IRL.jpg
- IMG/Cornerpanel_Spoolholder.png
- IMG/Extrude_This.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/SpoolHolder.stl
- STL/CornerPanel/CornerPanel_2.5mm.stl
- STL/CornerPanel/CornerPanel_2mm.stl
- STL/CornerPanel/CornerPanel_3.25mm.stl
- STL/CornerPanel/CornerPanel_3mm.stl
title: CornerPanel_SpoolHolder
