cad:
- CAD/Drawer_Version_C.step
- CAD/Drawer_Version_B.step
- CAD/Drawer_Version_A.step
description: Drawer in four different versions
images:
- Images/1.jpg
- Images/4.jpg
- Images/2.jpg
- Images/3.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/Drawer_A.stl
- STLs/Drawer_B.stl
- STLs/Drawer_C.stl
- STLs/Knob.stl
- STLs/Skirt_left.stl
- STLs/Skirt_right.stl
title: Drawer
