cad: []
description: Microswitch pod with JST-XH 4-pin connector
images:
- img/assembly.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Microswitch_Pod_Connector.stl
title: Microswitch Pod With Connector
