cad: []
description: relay-mount for 2x 2 channel relay modules.
images:
- relay_mount_printed.jpeg
- relay_mount2.png
- relay_mount1.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- relay_mount.stl
title: relay mount
