cad: []
description: Voron 0.1 Mounting brackets with/without RPi 4
images:
- Voron_V0_Duet_2_Wifi_Bracket_v14.png
- Duet2WifiMountingBracket.jpg
- Voron_V0_Duet_2_Wifi_Bracket_with_RPi_v14.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- Duet2Wifi_Mounting_Bracket.stl
- Duet2Wifi_Mounting_Bracket_with_RPi.stl
title: V0.1 Duet 2 Wifi mounting brackets
