cad:
- CAD/lgx_lite_side_can_mount.step
description: A side mounting for a CAN board (Huvud/SHT42) to the LGX Lite
images:
- Images/image.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl:
- STL/lgx_lite_side_can_mount.stl
title: LGX Lite CAN Side Mount
