cad: []
description: An alternative Din rail mount for BTT Octopus (PRO) boards
images:
- img/IMG-20210610-WA0001.jpg
- img/simple_bracket_STL.jpg
- img/octopus.svg
- img/octopus_inverted.svg
- img/STL.jpg
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl:
- STL/Octopus_limbs_bracket.stl
- STL/Simple_Octopus_Bracket_v2.stl
title: The Cephalopod limb (BTT Octopus PRO Bracket(s))
