cad:
- CAD/Rear_Umbilical.step
description: Rear Umbilical mounting solution including a relocated Y-Endstop
images:
- images/rear_umbilical.png
- Y_Endstop_Relocation/images/endstop.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/front_cover.stl
- STL/rear_mounting.stl
- Y_Endstop_Relocation/STL/y_endstop.stl
title: Rear Umbilical
