cad: []
description: 3Z mod for V1
images:
- images/installed_view.jpg
- images/bed_mount.jpg
- images/final_installation_view.jpg
- images/Top_rod_attachment.jpg
- images/bed_mount_installed.jpg
- images/full_assembly.jpg
- images/motor_mount_installed.jpg
- images/motor_mount_installation.jpg
mod_version: 1
printer_compatibility:
- V1.8
stl:
- STL/Bottom_Panel_Cutout_Cover.stl
- STL/Bottom_Panel_Cutout_Cover_2_Color.stl
- STL/Z_Bed_Mount_Front.stl
- STL/Z_Bed_Mount_Rear.stl
- STL/Z_Motor_Mount_Front.stl
- STL/Z_Motor_Mount_Rear.stl
title: V1 3Z
