cad:
- CAD/RunoutUnKlicky.step
description: Runout UnKlicky Sensor is a filament runout sensor with mounts for 1515
  and 2020 extrusions
images:
- images/cable.jpg
- images/pin.jpg
- images/designall.png
- images/nofilament.jpg
- images/top.jpg
- images/parts.jpg
- images/designtop.png
- images/filament.jpg
- images/magnets.jpg
- images/assembly.jpg
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VSW
- VT
stl:
- STLs/Base.stl
- STLs/Base_Collet.stl
- STLs/Base_PC4-M6.stl
- STLs/Pin.stl
- STLs/Roller.stl
- STLs/Top.stl
- STLs/Top_1515.stl
- STLs/Top_1515_NoNut.stl
- STLs/Top_2020.stl
title: Runout UnKlicky Sensor
