cad:
- VoronV0.1_FanSaver_rev0.6.step
description: A printable fix for overheating V0.1 blower fans
images:
- photos/FanSaver_Overview.png
- photos/Instructions-1.jpg
- photos/Instructions-3.jpg
- photos/Instructions-6.jpg
- photos/Instructions-7.jpg
- photos/FanSaver_ObjectRender.png
- photos/Instructions-2_ARROW.jpg
- photos/Instructions-4_ARROW.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- VoronV0.1_FanSaver_rev0.6b.stl
title: V0.1 FanSaver
