cad:
- CAD/DS18B20-sensor-mount.f3d
description: DS18B20 temperature sensor mount
images:
- Images/CAD_3.jpg
- Images/CAD_1.jpg
- Images/CAD_2.jpg
- Images/CAD_4.jpg
- Images/PIC_4.jpg
- Images/PIC_3.jpg
- Images/PIC_2.jpg
- Images/PIC_1.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STL/DS18B20-sensor-mount.stl
title: DS18B20 Sensor Mount
