cad:
- Hinges_v2.4_Mod.f3d
description: Simple mod of print in place door hinges, which uses m3 screws as shafts.
images:
- Door_Hinges_mod_with_M3_35mm.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- Door_Mount_left_x2.stl
- Door_Mount_right_x2.stl
- Profile_Mount_Nut_5mm_x4.stl
- Profile_Mount_Nut_6mm_x4.stl
title: Door hinges with M3 screws shafts
