cad: []
description: Mains plug panel for the RND_165-00057 Filter/Switch combination
images: []
mod_version: 1
printer_compatibility:
- V2.2
stl:
- mains_plug_panel_filtered_for_RND_165-00057.stl
- mains_plug_panel_filtered_for_RND_165-00057_ac_cover.stl
title: Mains plug panel for the RND_165-00057
