cad:
- CAD/OrangePi_Bracket.STEP
- CAD/OrangePi_Bracket.SLDPRT
description: A DIN rail mount for OrangePi LTS 3
images: []
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STLs/OrangePi_Bracket.STL
title: OrangePi 3 LTS DIN Rail bracket
