cad:
- CAD/Other_Idler_V2.f3d
- CAD/Other_Idler_V2.step
description: Allow usage of wider toolheads on the V2
images:
- Images/front.jpg
- Images/filekey.JPG
- Images/heatset.jpg
- Images/printset.JPG
- Images/comparison.jpg
- Images/Installed2.jpg
- Images/Installed.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/Front_Idler_Bottomx2.stl
- STL/Front_Idler_Topx2.stl
- STL/[a]_Idler_Carrierx2.stl
title: '"Other" Idlers Mod'
