cad:
- CAD/trident-euclid-carriage.step
description: A MGN-12 carriage with an inset mount for a Euclid Probe
images:
- Images/real-bottomview.jpg
- Images/real-frontview.jpg
- Images/CAD-bottomview.png
- Images/CAD-frontview.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STLs/x_carriage_frame_left_euclid.stl
- STLs/x_carriage_frame_right_euclid.stl
title: Euclid Probe Carriage
