cad:
- CAD/MKS_Mosfet_Mount.step
description: MKS Mosfet Mount based of the Trident Raspberry Pi Mount.
images:
- Images/MKS_Mosfet_Mount.png
- Images/MKS_Mosfet.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
stl:
- STL/MKS_Mosfet_Mount.stl
title: MKS Mosfet Mount
