cad:
- Monster8_DIN_clip.step
description: DIN mount for Makerbase Monster8 V1/V2 controller
images:
- example.jpg
- slicer.png
mod_version: 1
printer_compatibility:
- V2.4
- VT
stl:
- Monster8_DIN_clip_x2.stl
title: Monster8 DIN Rail Mounts
