cad: []
description: A mount for LED strips and Picam for the V0.1
images:
- camera_mount_detail.jpg
- printer_with_rails.jpg
- camera_view.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- rail.stl
- rail_camera_mount.stl
- rail_zip_tie_mount.stl
title: Lights, Camera, Voron
