cad: []
description: 60x20 Fan Mount for SW without tape
images:
- Images/installed.jpg
- Images/parts.jpg
mod_version: 1
printer_compatibility:
- VSW
stl:
- STLs/mount.stl
- STLs/mount_mirror.stl
title: SW Fan Mount No Tape
