cad:
- CAD/ToolheadPCBtoCANAdapter.step
description: A mount to enable side mounting of a CAN board (Huvud/SHT42) in Afterburner
  PCB spacing
images:
- Images/image.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- VT
stl:
- STL/ToolheadPCBtoCANAdapter.stl
title: Toolhead PCB to CAN Mount Adaptor
