cad: []
description: SSR, PowerSwitch, Adxl, Nameplate and color change printing
images:
- IMG/img1.jpg
- IMG/img9.jpg
- IMG/img8.jpg
- IMG/img5.jpg
- IMG/img6.jpg
- IMG/img7.jpg
- IMG/img3.jpg
- IMG/img2.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- V0.0/Skirt.stl
- V0.0/Skirt_adxl.stl
- V0.0/Skirt_EmptyNameplate.stl
- V0.0/Skirt_mirror.stl
- V0.0/Skirt_PowerSwitch.stl
- V0.0/Skirt_ssr.stl
- V0.1/Skirt.stl
- V0.1/Skirt_mirror.stl
title: V0 Skirt set
