cad:
- CAD/cable_tie_DIN_mount.f3d
description: A bracket for cable ties to route cables across DIN rails.
images:
- images/photo_railed.png
- images/db.png
- images/photo_bare.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STLs/cable_tie_DIN_mount.stl
title: cable tie DIN mount
