cad:
- jig.f3d
- jig.step
description: A jig help align extrusions to get a properly square frame
images:
- image.png
mod_version: 1
printer_compatibility:
- V2.4
stl:
- jig.stl
title: Voron 2.4 Extrusion Jig
