cad:
- CAD/2020_cover_one_side.f3d
- CAD/2020_cover_simmetric.f3d
description: Simple cover for extrusion with 6mm slot width
images:
- images/IMG_3238.jpeg
- images/IMG_3239.jpeg
- images/symmetric.jpg
- images/one_side.jpg
mod_version: 1
printer_compatibility:
- V2.4
stl:
- STL/slot_cover.stl
- STL/slot_cover_one_side.stl
title: 6mm slot cover
