cad:
- cad/v0.1_trident_skirt_remix.step
description: Trident style v0.1 skirt mix with 12864 Mini Lcd on front or plain skirt.
images:
- images/revnull2.jpg
- images/bottom-view.png
- images/lcd_cover_back_view.png
- images/lcd_back_to_connector.png
- images/corner-view.png
- images/connector.png
- images/skirt_screw_1.png
- images/v0.1_trident_skirt_remix_render.png
- images/skirt_screw_2.png
- images/connector_and_plate.png
- images/revnull1.jpg
- images/lcd_cover.png
- images/central_mount_plate.png
- images/lcd_back_to_connector_side_view.png
- images/v01-remixed-render.png
mod_version: 1
printer_compatibility:
- V0.2
stl:
- stl/connector_x1.stl
- stl/corner_back_left_c14_inlet_bom.stl
- stl/corner_front_left_x1.stl
- stl/corner_front_right_x1.stl
- stl/front_skirt_one_piece.stl
- stl/hartk_lcd_case_base_x1.stl
- stl/side_skirt_x2.stl
- stl/skirt_front_central_x1.stl
- stl/skirt_front_left_x1.stl
- stl/skirt_front_right_x1.stl
- stl/v0.1_trident_skirt_foot_rear_right_bowden_tube_connector_x1.stl
- stl/[a]_lcd_case_top_x1.stl
- stl/[a]_skirt_logo_x2.stl
title: V0.1 Trident skirt remix with 12864 LCD
