cad:
- CAD/V01_skirt_button.step
description: Buttons for V0.1 spec skirts
images:
- Images/picture0.jpg
- Images/picture1.jpg
- Images/cad_split.jpg
mod_version: 1
printer_compatibility:
- V0.2
stl:
- STLs/Button-arrow.stl
- STLs/Button-blank.stl
- STLs/Button-extrude.stl
- STLs/Button-heatbed.stl
- STLs/Button-hotend.stl
- STLs/Button-light.stl
- STLs/Button-park.stl
- STLs/Button-pauseresume.stl
- STLs/Button-power.stl
- STLs/Button-stop.stl
- STLs/Lock.stl
- STLs/Nut.stl
title: V0.1 Skirt buttons
