cad: []
description: 'Low-poly for Stealthburner + CW1 + PCB installations:'
images:
- Images/cover_front.png
- Images/cover_rear.png
- Images/cover_installed.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
stl:
- sb_cw1_pcb_cover-r1.stl
- sb_cw1_pcb_cover_clip-on_mount-r1.stl
title: Stealthburner + CW1 + PCB Cover
